export const USER_ROLES = [
  "STUDENT",
  "TEACHER",
  "ORGANIZATION_MANAGER",
  "PLATFORM_ADMINISTRATOR",
] as const;

export type UserRole = (typeof USER_ROLES)[number];

export const INTERFACE_LOCALES = ["en", "es"] as const;
export type InterfaceLocale = (typeof INTERFACE_LOCALES)[number];

export function namedRegionalTimeZones(): string[] {
  return Intl.supportedValuesOf("timeZone").filter((timeZone) =>
    timeZone.includes("/"),
  );
}

export interface UserIdentity {
  issuer: string;
  subject: string;
}

export interface Authenticator {
  authenticate(request: Request): Promise<UserIdentity | null>;
}

export const interfaceMessages = {
  en: {
    "workspace.eyebrow": "Student workspace",
    "workspace.greeting": "Hello, {name}",
    "workspace.introduction": "Your language-learning journey starts here.",
    "workspace.timeZone": "Time zone: {timeZone}",
    "workspace.settings": "Settings",
    "workspace.navigation": "Workspace navigation",
    "workspace.actingRole": "Acting role",
    "workspace.relationshipScope": "Scope: {scope}",
    "workspace.mobileDrawer": "Journey menu",
    "workspace.deepLink.eyebrow": "Workspace change",
    "workspace.deepLink.heading": "Change to the {role} workspace?",
    "workspace.deepLink.explanation": "Following this link will not change your acting role. Choose the role change explicitly or return safely to your current workspace.",
    "workspace.deepLink.change": "Change to {role}",
    "workspace.deepLink.return": "Return to {role}",
    "role.student": "Student",
    "role.teacher": "Teacher",
    "role.organizationManager": "Organization Manager",
    "role.platformAdministrator": "Platform Administrator",
    "workspace.student": "Student workspace",
    "workspace.teacher": "Teacher workspace",
    "workspace.organizationManager": "Organization Manager workspace",
    "workspace.platformAdministrator": "Platform Administrator workspace",
    "workspace.scope.student": "Your own learning",
    "workspace.scope.teacher": "Assigned Class Sessions",
    "workspace.scope.organizationManager": "Assigned Organization",
    "workspace.scope.platformAdministrator": "Marketplace-wide",
    "workspace.journey.student.discovery": "Discover Class Sessions",
    "workspace.journey.student.learning": "My learning",
    "workspace.journey.teacher.schedule": "Teaching schedule",
    "workspace.journey.teacher.availability": "Availability",
    "workspace.journey.organization.students": "Sponsored Students",
    "workspace.journey.organization.reports": "Reports",
    "workspace.journey.administration.operations": "Marketplace operations",
    "workspace.journey.administration.people": "People",
    "workspace.place.student.discovery": "Find your next Class Session.",
    "workspace.place.student.learning": "Review your learning journey.",
    "workspace.place.teacher.schedule": "Review your assigned Class Sessions.",
    "workspace.place.teacher.availability": "Manage when you are available to teach.",
    "workspace.place.organization.students": "Review Students in your assigned Organization.",
    "workspace.place.organization.reports": "Open privacy-bounded Sponsorship reports.",
    "workspace.place.administration.operations": "Review marketplace operations.",
    "workspace.place.administration.people": "Manage Users and Role Assignments.",
    "workspace.loading": "Opening your workspace…",
    "workspace.error": "We couldn't open your workspace. Try again.",
    "workspace.safeReturn": "Return safely",
    "preferences.title": "Choose your preferences",
    "preferences.savedTitle": "Your preferences",
    "preferences.suggestion": "These choices are suggested from this browser. They are not saved until you consent.",
    "preferences.locale": "Interface language",
    "preferences.locale.en": "English",
    "preferences.locale.es": "Spanish",
    "preferences.timeZone": "Display time zone",
    "preferences.timeZoneHelp": "Class Session times and calendar dates use this regional time zone.",
    "preferences.save": "Save preferences",
    "preferences.saving": "Saving preferences…",
    "preferences.saved": "Preferences saved.",
    "preferences.error": "We couldn't save your preferences. Try again.",
    "workspace.timeZonePreview": "Time zone preview",
    "workspace.currentInstant": "Local time when this page opened: {instant}",
    "workspace.localDate": "Calendar date",
    "workspace.localDateHelp": "This date starts at {instant} in universal time when interpreted in your Display Time Zone.",
    "workspace.localDateInvalid": "That calendar date has no unambiguous start in this Display Time Zone.",
    "auth.loading": "Checking your session…",
    "auth.error": "We couldn't verify your session. Try again.",
    "auth.signIn": "Sign in",
  },
  es: {
    "workspace.eyebrow": "Espacio de estudiante",
    "workspace.greeting": "Hola, {name}",
    "workspace.introduction": "Tu recorrido de aprendizaje comienza aquí.",
    "workspace.timeZone": "Zona horaria: {timeZone}",
    "workspace.settings": "Configuración",
    "workspace.navigation": "Navegación del espacio",
    "workspace.actingRole": "Rol activo",
    "workspace.relationshipScope": "Alcance: {scope}",
    "workspace.mobileDrawer": "Menú de recorridos",
    "workspace.deepLink.eyebrow": "Cambio de espacio",
    "workspace.deepLink.heading": "¿Cambiar al espacio de {role}?",
    "workspace.deepLink.explanation": "Seguir este enlace no cambiará tu rol activo. Elige el cambio de rol explícitamente o vuelve de forma segura a tu espacio actual.",
    "workspace.deepLink.change": "Cambiar a {role}",
    "workspace.deepLink.return": "Volver a {role}",
    "role.student": "estudiante",
    "role.teacher": "docente",
    "role.organizationManager": "responsable de organización",
    "role.platformAdministrator": "administración de la plataforma",
    "workspace.student": "Espacio de estudiante",
    "workspace.teacher": "Espacio de docente",
    "workspace.organizationManager": "Espacio de responsable de organización",
    "workspace.platformAdministrator": "Espacio de administración de la plataforma",
    "workspace.scope.student": "Tu propio aprendizaje",
    "workspace.scope.teacher": "Sesiones de clase asignadas",
    "workspace.scope.organizationManager": "Organización asignada",
    "workspace.scope.platformAdministrator": "Todo el mercado",
    "workspace.journey.student.discovery": "Descubrir sesiones de clase",
    "workspace.journey.student.learning": "Mi aprendizaje",
    "workspace.journey.teacher.schedule": "Horario docente",
    "workspace.journey.teacher.availability": "Disponibilidad",
    "workspace.journey.organization.students": "Estudiantes patrocinados",
    "workspace.journey.organization.reports": "Informes",
    "workspace.journey.administration.operations": "Operaciones del mercado",
    "workspace.journey.administration.people": "Personas",
    "workspace.place.student.discovery": "Encuentra tu próxima sesión de clase.",
    "workspace.place.student.learning": "Revisa tu recorrido de aprendizaje.",
    "workspace.place.teacher.schedule": "Revisa tus sesiones de clase asignadas.",
    "workspace.place.teacher.availability": "Gestiona cuándo estás disponible para enseñar.",
    "workspace.place.organization.students": "Revisa a los estudiantes de tu organización asignada.",
    "workspace.place.organization.reports": "Abre informes de patrocinio con privacidad limitada.",
    "workspace.place.administration.operations": "Revisa las operaciones del mercado.",
    "workspace.place.administration.people": "Gestiona usuarios y asignaciones de rol.",
    "workspace.loading": "Abriendo tu espacio…",
    "workspace.error": "No pudimos abrir tu espacio. Inténtalo de nuevo.",
    "workspace.safeReturn": "Volver de forma segura",
    "preferences.title": "Elige tus preferencias",
    "preferences.savedTitle": "Tus preferencias",
    "preferences.suggestion": "Estas opciones son sugerencias de este navegador. No se guardan hasta que des tu consentimiento.",
    "preferences.locale": "Idioma de la interfaz",
    "preferences.locale.en": "Inglés",
    "preferences.locale.es": "Español",
    "preferences.timeZone": "Zona horaria de visualización",
    "preferences.timeZoneHelp": "Las horas de las sesiones de clase y las fechas del calendario usan esta zona horaria regional.",
    "preferences.save": "Guardar preferencias",
    "preferences.saving": "Guardando preferencias…",
    "preferences.saved": "Preferencias guardadas.",
    "preferences.error": "No pudimos guardar tus preferencias. Inténtalo de nuevo.",
    "workspace.timeZonePreview": "Vista previa de la zona horaria",
    "workspace.currentInstant": "Hora local cuando se abrió esta página: {instant}",
    "workspace.localDate": "Fecha del calendario",
    "workspace.localDateHelp": "Esta fecha comienza a las {instant} en tiempo universal cuando se interpreta en tu zona horaria de visualización.",
    "workspace.localDateInvalid": "Esa fecha del calendario no tiene un comienzo inequívoco en esta zona horaria de visualización.",
    "auth.loading": "Comprobando tu sesión…",
    "auth.error": "No pudimos verificar tu sesión. Inténtalo de nuevo.",
    "auth.signIn": "Iniciar sesión",
  },
} as const;
