export const USER_ROLES = [
  "STUDENT",
  "TEACHER",
  "ORGANIZATION_MANAGER",
  "PLATFORM_ADMINISTRATOR",
] as const;

export type UserRole = (typeof USER_ROLES)[number];

export const INTERFACE_LOCALES = ["en", "es"] as const;
export type InterfaceLocale = (typeof INTERFACE_LOCALES)[number];

export function namedRegionalTimeZones(): string[] {
  return Intl.supportedValuesOf("timeZone").filter((timeZone) =>
    timeZone.includes("/"),
  );
}

export interface UserIdentity {
  issuer: string;
  subject: string;
}

export interface Authenticator {
  authenticate(request: Request): Promise<UserIdentity | null>;
}

export const interfaceMessages = {
  en: {
    "workspace.eyebrow": "Student workspace",
    "workspace.greeting": "Hello, {name}",
    "workspace.introduction": "Your language-learning journey starts here.",
    "workspace.timeZone": "Time zone: {timeZone}",
    "workspace.settings": "Settings",
    "workspace.navigation": "Workspace navigation",
    "workspace.actingRole": "Acting role",
    "workspace.relationshipScope": "Scope: {scope}",
    "workspace.mobileDrawer": "Journey menu",
    "workspace.deepLink.eyebrow": "Workspace change",
    "workspace.deepLink.heading": "Change to the {role} workspace?",
    "workspace.deepLink.explanation": "Following this link will not change your acting role. Choose the role change explicitly or return safely to your current workspace.",
    "workspace.deepLink.change": "Change to {role}",
    "workspace.deepLink.return": "Return to {role}",
    "role.student": "Student",
    "role.teacher": "Teacher",
    "role.organizationManager": "Organization Manager",
    "role.platformAdministrator": "Platform Administrator",
    "workspace.student": "Student workspace",
    "workspace.teacher": "Teacher workspace",
    "workspace.organizationManager": "Organization Manager workspace",
    "workspace.platformAdministrator": "Platform Administrator workspace",
    "workspace.scope.student": "Your own learning",
    "workspace.scope.teacher": "Assigned Class Sessions",
    "workspace.scope.organizationManager": "Assigned Organization",
    "workspace.scope.platformAdministrator": "Marketplace-wide",
    "workspace.journey.student.discovery": "Discover Class Sessions",
    "workspace.journey.student.learning": "My learning",
    "workspace.journey.teacher.schedule": "Teaching schedule",
    "workspace.journey.teacher.availability": "Availability",
    "workspace.journey.organization.students": "Sponsored Students",
    "workspace.journey.organization.reports": "Reports",
    "workspace.journey.administration.operations": "Marketplace operations",
    "workspace.journey.administration.people": "People",
    "workspace.place.student.discovery": "Find your next Class Session.",
    "workspace.place.student.learning": "Review your learning journey.",
    "workspace.place.teacher.schedule": "Review your assigned Class Sessions.",
    "workspace.place.teacher.availability": "Manage when you are available to teach.",
    "workspace.place.organization.students": "Review Students in your assigned Organization.",
    "workspace.place.organization.reports": "Open privacy-bounded Sponsorship reports.",
    "workspace.place.administration.operations": "Review marketplace operations.",
    "workspace.place.administration.people": "Manage Users and Role Assignments.",
    "workspace.loading": "Opening your workspace…",
    "workspace.error": "We couldn't open your workspace. Try again.",
    "workspace.safeReturn": "Return safely",
    "preferences.title": "Choose your preferences",
    "preferences.savedTitle": "Your preferences",
    "preferences.suggestion": "These choices are suggested from this browser. They are not saved until you consent.",
    "preferences.locale": "Interface language",
    "preferences.locale.en": "English",
    "preferences.locale.es": "Spanish",
    "preferences.timeZone": "Display time zone",
    "preferences.timeZoneHelp": "Class Session times and calendar dates use this regional time zone.",
    "preferences.save": "Save preferences",
    "preferences.saving": "Saving preferences…",
    "preferences.saved": "Preferences saved.",
    "preferences.error": "We couldn't save your preferences. Try again.",
    "workspace.timeZonePreview": "Time zone preview",
    "workspace.currentInstant": "Local time when this page opened: {instant}",
    "workspace.localDate": "Calendar date",
    "workspace.localDateHelp": "This date starts at {instant} in universal time when interpreted in your Display Time Zone.",
    "workspace.localDateInvalid": "That calendar date has no unambiguous start in this Display Time Zone.",
    "curriculum.loading": "Loading curriculum administration…",
    "curriculum.error": "We couldn't update the curriculum. Review the details and try again.",
    "curriculum.sampleBadge": "Sample curriculum",
    "curriculum.title": "Curriculum administration",
    "curriculum.notice": "Illustrative, incomplete curriculum for this public demonstration; it is not a formally certified language program.",
    "curriculum.catalog": "Courses and Lesson Units",
    "curriculum.empty": "No Courses have been created yet.",
    "curriculum.active": "Active",
    "curriculum.retired": "Retired",
    "curriculum.retire": "Retire Lesson Unit",
    "curriculum.newCourse": "Create a Course",
    "curriculum.targetLanguage": "Target language code",
    "curriculum.level": "Curriculum Level",
    "curriculum.courseTitle": "Course title",
    "curriculum.summary": "Summary",
    "curriculum.createCourse": "Create Course",
    "curriculum.courseCreated": "Course created.",
    "curriculum.editCourse": "Edit Course details",
    "curriculum.saveCourse": "Save Course",
    "curriculum.courseUpdated": "Course updated.",
    "curriculum.newUnit": "Add a Lesson Unit",
    "curriculum.course": "Course",
    "curriculum.unitTitle": "Lesson Unit title",
    "curriculum.objectives": "Objectives",
    "curriculum.objectivesHelp": "Enter one objective per line.",
    "curriculum.topics": "Topics",
    "curriculum.createUnit": "Create Lesson Unit",
    "curriculum.unitCreated": "Lesson Unit created.",
    "curriculum.unitRetired": "Lesson Unit retired; its history remains available.",
    "curriculum.editUnit": "Edit Lesson Unit",
    "curriculum.saveUnit": "Save Lesson Unit",
    "curriculum.unitUpdated": "Lesson Unit updated.",
    "curriculum.identityLocked": "Instructional identity is locked because this Lesson Unit has been published.",
    "curriculum.moveUp": "Move up",
    "curriculum.moveDown": "Move down",
    "curriculum.unitReordered": "Lesson Unit order updated.",
    "curriculum.replacement": "Replacement Lesson Unit",
    "curriculum.noReplacement": "No replacement",
    "curriculum.manageTopic": "Manage a localized Topic",
    "curriculum.topicKey": "Topic key",
    "curriculum.labelEn": "English label",
    "curriculum.labelEs": "Spanish label",
    "curriculum.saveTopic": "Save Topic",
    "curriculum.topicSaved": "Topic saved in English and Spanish.",
    "curriculum.addMaterial": "Add Lesson Material",
    "curriculum.unit": "Lesson Unit",
    "curriculum.materialKind": "Material form",
    "curriculum.structuredText": "Structured text",
    "curriculum.httpsReference": "HTTPS reference",
    "curriculum.materialTitle": "Material title",
    "curriculum.materialHeading": "Structured heading",
    "curriculum.materialBody": "Structured paragraph",
    "curriculum.materialList": "Structured list (one item per line)",
    "curriculum.materialEmphasis": "Structured emphasis",
    "curriculum.httpsUrl": "HTTPS URL",
    "curriculum.publisher": "Publisher",
    "curriculum.addMaterialAction": "Add Lesson Material",
    "curriculum.materialAdded": "Lesson Material added.",
    "curriculum.reviseMaterial": "Revise a Lesson Material",
    "curriculum.reviseMaterialAction": "Save Lesson Material revision",
    "curriculum.materialRevised": "Lesson Material revised.",
    "curriculum.teacherProfile": "Manage a Teacher Profile",
    "curriculum.teacherUserId": "Teacher User ID",
    "curriculum.pronouns": "Pronouns",
    "curriculum.profileImageUrl": "Profile image HTTPS URL",
    "curriculum.biography": "Professional biography",
    "curriculum.teachingTopics": "Teaching Topics",
    "curriculum.saveProfile": "Save Teacher Profile",
    "curriculum.profileSaved": "Teacher Profile saved.",
    "curriculum.teacherQualification": "Manage a Teacher Qualification",
    "curriculum.action": "Action",
    "curriculum.grant": "Grant",
    "curriculum.remove": "Remove",
    "curriculum.applyQualification": "Apply Teacher Qualification change",
    "curriculum.qualificationGranted": "Teacher Qualification granted and the Teacher was notified.",
    "curriculum.qualificationRemoved": "Teacher Qualification removed and the Teacher was notified.",
    "curriculum.qualificationBlocked": "Resolve the listed future Class Sessions before removing this Teacher Qualification.",
    "curriculum.teachers": "Teacher Profiles and Qualifications",
    "curriculum.teacherId": "Teacher User ID",
    "teacher-qualification.granted.teacher": "Teacher Qualification granted for {targetLanguage} {curriculumLevel} on {effectiveTime, date, long} at {effectiveTime, time, short}.",
    "teacher-qualification.removed.teacher": "Teacher Qualification removed for {targetLanguage} {curriculumLevel} on {effectiveTime, date, long} at {effectiveTime, time, short}.",
    "auth.loading": "Checking your session…",
    "auth.error": "We couldn't verify your session. Try again.",
    "auth.signIn": "Sign in",
  },
  es: {
    "workspace.eyebrow": "Espacio de estudiante",
    "workspace.greeting": "Hola, {name}",
    "workspace.introduction": "Tu recorrido de aprendizaje comienza aquí.",
    "workspace.timeZone": "Zona horaria: {timeZone}",
    "workspace.settings": "Configuración",
    "workspace.navigation": "Navegación del espacio",
    "workspace.actingRole": "Rol activo",
    "workspace.relationshipScope": "Alcance: {scope}",
    "workspace.mobileDrawer": "Menú de recorridos",
    "workspace.deepLink.eyebrow": "Cambio de espacio",
    "workspace.deepLink.heading": "¿Cambiar al espacio de {role}?",
    "workspace.deepLink.explanation": "Seguir este enlace no cambiará tu rol activo. Elige el cambio de rol explícitamente o vuelve de forma segura a tu espacio actual.",
    "workspace.deepLink.change": "Cambiar a {role}",
    "workspace.deepLink.return": "Volver a {role}",
    "role.student": "estudiante",
    "role.teacher": "docente",
    "role.organizationManager": "responsable de organización",
    "role.platformAdministrator": "administración de la plataforma",
    "workspace.student": "Espacio de estudiante",
    "workspace.teacher": "Espacio de docente",
    "workspace.organizationManager": "Espacio de responsable de organización",
    "workspace.platformAdministrator": "Espacio de administración de la plataforma",
    "workspace.scope.student": "Tu propio aprendizaje",
    "workspace.scope.teacher": "Sesiones de clase asignadas",
    "workspace.scope.organizationManager": "Organización asignada",
    "workspace.scope.platformAdministrator": "Todo el mercado",
    "workspace.journey.student.discovery": "Descubrir sesiones de clase",
    "workspace.journey.student.learning": "Mi aprendizaje",
    "workspace.journey.teacher.schedule": "Horario docente",
    "workspace.journey.teacher.availability": "Disponibilidad",
    "workspace.journey.organization.students": "Estudiantes patrocinados",
    "workspace.journey.organization.reports": "Informes",
    "workspace.journey.administration.operations": "Operaciones del mercado",
    "workspace.journey.administration.people": "Personas",
    "workspace.place.student.discovery": "Encuentra tu próxima sesión de clase.",
    "workspace.place.student.learning": "Revisa tu recorrido de aprendizaje.",
    "workspace.place.teacher.schedule": "Revisa tus sesiones de clase asignadas.",
    "workspace.place.teacher.availability": "Gestiona cuándo estás disponible para enseñar.",
    "workspace.place.organization.students": "Revisa a los estudiantes de tu organización asignada.",
    "workspace.place.organization.reports": "Abre informes de patrocinio con privacidad limitada.",
    "workspace.place.administration.operations": "Revisa las operaciones del mercado.",
    "workspace.place.administration.people": "Gestiona usuarios y asignaciones de rol.",
    "workspace.loading": "Abriendo tu espacio…",
    "workspace.error": "No pudimos abrir tu espacio. Inténtalo de nuevo.",
    "workspace.safeReturn": "Volver de forma segura",
    "preferences.title": "Elige tus preferencias",
    "preferences.savedTitle": "Tus preferencias",
    "preferences.suggestion": "Estas opciones son sugerencias de este navegador. No se guardan hasta que des tu consentimiento.",
    "preferences.locale": "Idioma de la interfaz",
    "preferences.locale.en": "Inglés",
    "preferences.locale.es": "Español",
    "preferences.timeZone": "Zona horaria de visualización",
    "preferences.timeZoneHelp": "Las horas de las sesiones de clase y las fechas del calendario usan esta zona horaria regional.",
    "preferences.save": "Guardar preferencias",
    "preferences.saving": "Guardando preferencias…",
    "preferences.saved": "Preferencias guardadas.",
    "preferences.error": "No pudimos guardar tus preferencias. Inténtalo de nuevo.",
    "workspace.timeZonePreview": "Vista previa de la zona horaria",
    "workspace.currentInstant": "Hora local cuando se abrió esta página: {instant}",
    "workspace.localDate": "Fecha del calendario",
    "workspace.localDateHelp": "Esta fecha comienza a las {instant} en tiempo universal cuando se interpreta en tu zona horaria de visualización.",
    "workspace.localDateInvalid": "Esa fecha del calendario no tiene un comienzo inequívoco en esta zona horaria de visualización.",
    "curriculum.loading": "Cargando la administración del currículo…",
    "curriculum.error": "No pudimos actualizar el currículo. Revisa los datos e inténtalo de nuevo.",
    "curriculum.sampleBadge": "Currículo de muestra",
    "curriculum.title": "Administración del currículo",
    "curriculum.notice": "Currículo ilustrativo e incompleto para esta demostración pública; no es un programa de idiomas con certificación formal.",
    "curriculum.catalog": "Cursos y unidades didácticas",
    "curriculum.empty": "Todavía no se ha creado ningún curso.",
    "curriculum.active": "Activa",
    "curriculum.retired": "Retirada",
    "curriculum.retire": "Retirar unidad didáctica",
    "curriculum.newCourse": "Crear un curso",
    "curriculum.targetLanguage": "Código del idioma objetivo",
    "curriculum.level": "Nivel curricular",
    "curriculum.courseTitle": "Título del curso",
    "curriculum.summary": "Resumen",
    "curriculum.createCourse": "Crear curso",
    "curriculum.courseCreated": "Curso creado.",
    "curriculum.editCourse": "Editar datos del curso",
    "curriculum.saveCourse": "Guardar curso",
    "curriculum.courseUpdated": "Curso actualizado.",
    "curriculum.newUnit": "Añadir una unidad didáctica",
    "curriculum.course": "Curso",
    "curriculum.unitTitle": "Título de la unidad didáctica",
    "curriculum.objectives": "Objetivos",
    "curriculum.objectivesHelp": "Escribe un objetivo por línea.",
    "curriculum.topics": "Temas",
    "curriculum.createUnit": "Crear unidad didáctica",
    "curriculum.unitCreated": "Unidad didáctica creada.",
    "curriculum.unitRetired": "Unidad didáctica retirada; su historial sigue disponible.",
    "curriculum.editUnit": "Editar unidad didáctica",
    "curriculum.saveUnit": "Guardar unidad didáctica",
    "curriculum.unitUpdated": "Unidad didáctica actualizada.",
    "curriculum.identityLocked": "La identidad didáctica está bloqueada porque esta unidad ya se publicó.",
    "curriculum.moveUp": "Subir",
    "curriculum.moveDown": "Bajar",
    "curriculum.unitReordered": "Orden de la unidad didáctica actualizado.",
    "curriculum.replacement": "Unidad didáctica de reemplazo",
    "curriculum.noReplacement": "Sin reemplazo",
    "curriculum.manageTopic": "Gestionar un tema localizado",
    "curriculum.topicKey": "Clave del tema",
    "curriculum.labelEn": "Etiqueta en inglés",
    "curriculum.labelEs": "Etiqueta en español",
    "curriculum.saveTopic": "Guardar tema",
    "curriculum.topicSaved": "Tema guardado en inglés y español.",
    "curriculum.addMaterial": "Añadir material de unidad",
    "curriculum.unit": "Unidad didáctica",
    "curriculum.materialKind": "Forma del material",
    "curriculum.structuredText": "Texto estructurado",
    "curriculum.httpsReference": "Referencia HTTPS",
    "curriculum.materialTitle": "Título del material",
    "curriculum.materialHeading": "Encabezado estructurado",
    "curriculum.materialBody": "Párrafo estructurado",
    "curriculum.materialList": "Lista estructurada (un elemento por línea)",
    "curriculum.materialEmphasis": "Énfasis estructurado",
    "curriculum.httpsUrl": "URL HTTPS",
    "curriculum.publisher": "Editorial",
    "curriculum.addMaterialAction": "Añadir material de unidad",
    "curriculum.materialAdded": "Material de unidad añadido.",
    "curriculum.reviseMaterial": "Revisar un material de unidad",
    "curriculum.reviseMaterialAction": "Guardar revisión del material",
    "curriculum.materialRevised": "Material de unidad revisado.",
    "curriculum.teacherProfile": "Gestionar un perfil docente",
    "curriculum.teacherUserId": "ID de usuario docente",
    "curriculum.pronouns": "Pronombres",
    "curriculum.profileImageUrl": "URL HTTPS de la imagen de perfil",
    "curriculum.biography": "Biografía profesional",
    "curriculum.teachingTopics": "Temas de enseñanza",
    "curriculum.saveProfile": "Guardar perfil docente",
    "curriculum.profileSaved": "Perfil docente guardado.",
    "curriculum.teacherQualification": "Gestionar una cualificación docente",
    "curriculum.action": "Acción",
    "curriculum.grant": "Conceder",
    "curriculum.remove": "Retirar",
    "curriculum.applyQualification": "Aplicar cambio de cualificación docente",
    "curriculum.qualificationGranted": "Cualificación docente concedida y notificada a la persona docente.",
    "curriculum.qualificationRemoved": "Cualificación docente retirada y notificada a la persona docente.",
    "curriculum.qualificationBlocked": "Resuelve las sesiones de clase futuras indicadas antes de retirar esta cualificación docente.",
    "curriculum.teachers": "Perfiles y cualificaciones docentes",
    "curriculum.teacherId": "ID de usuario docente",
    "teacher-qualification.granted.teacher": "Cualificación docente concedida para {targetLanguage} {curriculumLevel} el {effectiveTime, date, long} a las {effectiveTime, time, short}.",
    "teacher-qualification.removed.teacher": "Cualificación docente retirada para {targetLanguage} {curriculumLevel} el {effectiveTime, date, long} a las {effectiveTime, time, short}.",
    "auth.loading": "Comprobando tu sesión…",
    "auth.error": "No pudimos verificar tu sesión. Inténtalo de nuevo.",
    "auth.signIn": "Iniciar sesión",
  },
} as const;
