export const USER_ROLES = [
  "STUDENT",
  "TEACHER",
  "ORGANIZATION_MANAGER",
  "PLATFORM_ADMINISTRATOR",
] as const;

export type UserRole = (typeof USER_ROLES)[number];
export type AttendanceOutcome = "ATTENDED" | "NO_SHOW";

export const FEEDBACK_SKILLS = ["LISTENING", "READING", "SPOKEN_INTERACTION", "SPOKEN_PRODUCTION", "WRITING", "VOCABULARY", "GRAMMAR", "PRONUNCIATION"] as const;
export type FeedbackSkill = (typeof FEEDBACK_SKILLS)[number];
export const SESSION_RATING_POSITIVE_TAGS = ["CLEAR_EXPLANATIONS", "SUPPORTIVE", "ENGAGING", "USEFUL_PRACTICE"] as const;
export type SessionRatingPositiveTag = (typeof SESSION_RATING_POSITIVE_TAGS)[number];
export const SESSION_RATING_IMPROVEMENT_TAGS = ["PACING", "AUDIO_QUALITY", "MORE_CORRECTION", "MORE_SPEAKING_TIME"] as const;
export type SessionRatingImprovementTag = (typeof SESSION_RATING_IMPROVEMENT_TAGS)[number];

export function feedbackWindowIsOpen(now: Date, eligibleFrom: Date) {
  return now <= feedbackDeadline(eligibleFrom);
}

export function sessionRatingWindowIsOpen(now: Date, eligibleFrom: Date) {
  return now <= sessionRatingDeadline(eligibleFrom);
}

export function feedbackDeadline(eligibleFrom: Date) {
  return new Date(eligibleFrom.getTime() + 48 * 60 * 60_000);
}

export function sessionRatingDeadline(eligibleFrom: Date) {
  return new Date(eligibleFrom.getTime() + 7 * 24 * 60 * 60_000);
}

export function establishesLessonUnitCompletion(outcomes: readonly AttendanceOutcome[]) {
  return outcomes.reduce((attended, outcome) => attended || outcome === "ATTENDED", false);
}

const BOOKING_DEADLINE_MILLISECONDS = 30 * 60_000;
const REFUND_DEADLINE_MILLISECONDS = 24 * 60 * 60_000;
const WAITLIST_DEADLINE_MILLISECONDS = 2 * 60 * 60_000;

export function bookingWindowIsOpen(now: Date, startsAt: Date) {
  return startsAt.getTime() - now.getTime() >= BOOKING_DEADLINE_MILLISECONDS;
}

export function studentCancellationCreditOutcome(now: Date, startsAt: Date) {
  const timeUntilStart = startsAt.getTime() - now.getTime();
  if (timeUntilStart <= 0) return "CLOSED" as const;
  return timeUntilStart >= REFUND_DEADLINE_MILLISECONDS
    ? "REFUND" as const
    : "FORFEIT" as const;
}

export function waitlistExpiresAt(startsAt: Date) {
  return new Date(startsAt.getTime() - WAITLIST_DEADLINE_MILLISECONDS);
}

export function waitlistIsOpen(now: Date, startsAt: Date) {
  return now < waitlistExpiresAt(startsAt);
}

export const INTERFACE_LOCALES = ["en", "es"] as const;
export type InterfaceLocale = (typeof INTERFACE_LOCALES)[number];

export function namedRegionalTimeZones(): string[] {
  return Intl.supportedValuesOf("timeZone").filter((timeZone) =>
    timeZone.includes("/"),
  );
}

export interface UserIdentity {
  issuer: string;
  subject: string;
}

export interface Authenticator {
  authenticate(request: Request): Promise<UserIdentity | null>;
}

export const interfaceMessages = {
  en: {
    "workspace.eyebrow": "Student workspace",
    "workspace.greeting": "Hello, {name}",
    "workspace.introduction": "Your language-learning journey starts here.",
    "workspace.timeZone": "Time zone: {timeZone}",
    "workspace.settings": "Settings",
    "notifications.title": "Notifications",
    "notifications.loading": "Loading notifications…",
    "notifications.error": "We couldn't load your notifications. Try again.",
    "notifications.empty": "You have no notifications.",
    "notifications.markRead": "Mark as read",
    "notifications.read": "Read",
    "administratorTasks.title": "Administrator tasks",
    "administratorTasks.loading": "Loading administrator tasks…",
    "administratorTasks.error": "We couldn't load administrator tasks. Try again.",
    "administratorTasks.empty": "There is no unresolved administrator work.",
    "administratorTasks.notificationDelivery": "Reconcile an exhausted notification delivery.",
    "administratorTasks.correlation": "Correlation reference",
    "administratorTasks.channel": "Channel",
    "administratorTasks.message": "Message policy",
    "administratorTasks.reason": "Resolution reason",
    "administratorTasks.resolve": "Resolve task",
    "administratorTasks.resolved": "Task resolved.",
    "workspace.navigation": "Workspace navigation",
    "workspace.actingRole": "Acting role",
    "workspace.relationshipScope": "Scope: {scope}",
    "workspace.mobileDrawer": "Journey menu",
    "workspace.deepLink.eyebrow": "Workspace change",
    "workspace.deepLink.heading": "Change to the {role} workspace?",
    "workspace.deepLink.explanation": "Following this link will not change your acting role. Choose the role change explicitly or return safely to your current workspace.",
    "workspace.deepLink.change": "Change to {role}",
    "workspace.deepLink.return": "Return to {role}",
    "role.student": "Student",
    "role.teacher": "Teacher",
    "role.organizationManager": "Organization Manager",
    "role.platformAdministrator": "Platform Administrator",
    "workspace.student": "Student workspace",
    "workspace.teacher": "Teacher workspace",
    "workspace.organizationManager": "Organization Manager workspace",
    "workspace.platformAdministrator": "Platform Administrator workspace",
    "workspace.scope.student": "Your own learning",
    "workspace.scope.teacher": "Assigned Class Sessions",
    "workspace.scope.organizationManager": "Assigned Organization",
    "workspace.scope.platformAdministrator": "Marketplace-wide",
    "workspace.journey.student.discovery": "Discover Class Sessions",
    "workspace.journey.student.learning": "My learning",
    "workspace.journey.teacher.schedule": "Teaching schedule",
    "workspace.journey.teacher.availability": "Availability",
    "workspace.journey.organization.students": "Sponsored Students",
    "workspace.journey.organization.reports": "Reports",
    "workspace.journey.administration.operations": "Marketplace operations",
    "workspace.journey.administration.people": "People",
    "workspace.place.student.discovery": "Find your next Class Session.",
    "workspace.place.student.learning": "Review your learning journey.",
    "workspace.place.teacher.schedule": "Review your assigned Class Sessions.",
    "workspace.place.teacher.availability": "Manage when you are available to teach.",
    "workspace.place.organization.students": "Review Students in your assigned Organization.",
    "workspace.place.organization.reports": "Open privacy-bounded Sponsorship reports.",
    "workspace.place.administration.operations": "Review marketplace operations.",
    "workspace.place.administration.people": "Manage Users and Role Assignments.",
    "workspace.loading": "Opening your workspace…",
    "workspace.error": "We couldn't open your workspace. Try again.",
    "workspace.safeReturn": "Return safely",
    "preferences.title": "Choose your preferences",
    "preferences.savedTitle": "Your preferences",
    "preferences.suggestion": "These choices are suggested from this browser. They are not saved until you consent.",
    "preferences.locale": "Interface language",
    "preferences.locale.en": "English",
    "preferences.locale.es": "Spanish",
    "preferences.timeZone": "Display time zone",
    "preferences.timeZoneHelp": "Class Session times and calendar dates use this regional time zone.",
    "preferences.save": "Save preferences",
    "preferences.saving": "Saving preferences…",
    "preferences.saved": "Preferences saved.",
    "preferences.error": "We couldn't save your preferences. Try again.",
    "workspace.timeZonePreview": "Time zone preview",
    "workspace.currentInstant": "Local time when this page opened: {instant}",
    "workspace.localDate": "Calendar date",
    "workspace.localDateHelp": "This date starts at {instant} in universal time when interpreted in your Display Time Zone.",
    "workspace.localDateInvalid": "That calendar date has no unambiguous start in this Display Time Zone.",
    "credit-adjustment.committed.student": "Class Credit adjustment: {amount, number, ::sign-always} credits. Available balance: {availableBalance, number}. Reason: {reason}",
    "subscription.activated.student": "Subscription activated with {amount, number} Class Credits. Available balance: {availableBalance, number}. Next grant: {nextAnniversaryAt, date, long} at {nextAnniversaryAt, time, short}.",
    "subscription.renewed.student": "Subscription renewed with {amount, number} Class Credits. Available balance: {availableBalance, number}. Next grant: {nextAnniversaryAt, date, long} at {nextAnniversaryAt, time, short}.",
    "subscription.cancellation-scheduled.student": "Subscription cancellation is scheduled for {cancellationEffectiveAt, date, long} at {cancellationEffectiveAt, time, short}. No grant occurs then, and your existing Class Credits remain.",
    "subscription.cancellation-undone.student": "Subscription cancellation was undone. No immediate Class Credits were granted. The next grant remains {nextAnniversaryAt, date, long} at {nextAnniversaryAt, time, short}.",
    "classCredits.studentTitle": "My Class Credits",
    "classCredits.adminTitle": "Class Credit administration",
    "classCredits.studentUserId": "Student User ID",
    "classCredits.inspect": "Inspect Class Credits",
    "classCredits.loading": "Loading Class Credits…",
    "classCredits.loadError": "We couldn't load Class Credits. Try again.",
    "classCredits.balance": "{balance, plural, one {# Class Credit available} other {# Class Credits available}}",
    "classCredits.ledger": "Class Credit ledger",
    "classCredits.empty": "No Class Credit activity yet.",
    "classCredits.amount": "Signed adjustment",
    "classCredits.amountHelp": "Use a positive whole number to grant or a negative whole number to decrease the balance.",
    "classCredits.reason": "Student-visible reason",
    "classCredits.adjust": "Apply Credit Adjustment",
    "classCredits.adjusted": "Credit Adjustment applied and the Student was notified.",
    "classCredits.notFound": "Choose a User with a Student Role Assignment.",
    "classCredits.error": "We couldn't apply that Credit Adjustment. Review the available balance, reason, and request identifier.",
    "classCredits.source.creditAdjustment": "Credit Adjustment",
    "classCredits.source.subscriptionGrant": "Subscription grant",
    "classCredits.source.organizationGrant": "Organization credit grant",
    "classCredits.source.bookingDeduction": "Booking deduction",
    "classCredits.source.bookingRefund": "Booking refund",
    "classCredits.reference": "Reference: {reference}",
    "subscription.title": "My Subscription",
    "subscription.loading": "Loading Subscription…",
    "subscription.loadError": "We couldn't load your Subscription. Try again.",
    "subscription.none": "No Subscription is active.",
    "subscription.state.active": "Active",
    "subscription.state.cancellationScheduled": "Cancellation scheduled",
    "subscription.state.cancelled": "Cancelled",
    "subscription.nextAnniversary": "Next Class Credit grant: {date}",
    "subscription.cancellationEffective": "Cancellation takes effect: {date}",
    "subscription.scheduleCancellation": "Schedule cancellation",
    "subscription.keep": "Keep Subscription",
    "subscription.scheduled": "Cancellation scheduled. Your existing Class Credits remain.",
    "subscription.undone": "Cancellation undone. No immediate Class Credits were granted.",
    "subscription.changeError": "We couldn't change your Subscription. Try again with the same request.",
    "sponsorship.disclosure.benefit": "Eight Class Credits at acceptance and eight more on each monthly anniversary while the Sponsorship remains active.",
    "sponsorship.disclosure.visibleData": "Your attendance and Course Progress during the Sponsorship.",
    "sponsorship.disclosure.excludedData": "Private Learning Feedback, Session Ratings, payment details, and your total Class Credit balance.",
    "sponsorship-invitation.created.student": "{organizationName} invited you to a Sponsorship offering eight Class Credits at acceptance and eight on each monthly anniversary, with attendance and Course Progress visible to the Organization during the Sponsorship. Review the complete disclosure before deciding. This invitation expires {expiresAt, date, long} at {expiresAt, time, short}. No Sponsorship or reporting access exists until you accept.",
    "sponsorship-invitation.created.manager": "Sponsorship Invitation sent to {studentDisplayName}, expiring {expiresAt, date, long} at {expiresAt, time, short}.",
    "sponsorship-invitation.accepted.student": "Sponsorship with {organizationName} started and granted {amount, number} Class Credits. Available balance: {availableBalance, number}. Next grant: {nextAnniversaryAt, date, long} at {nextAnniversaryAt, time, short}. The Organization can see your attendance and Course Progress during the Sponsorship. Either you or the Organization may end the Sponsorship at any time.",
    "sponsorship-invitation.accepted.manager": "{studentDisplayName} accepted the Sponsorship Invitation. Reporting begins {acceptedAt, date, long} at {acceptedAt, time, short}.",
    "sponsorship-invitation.declined.student": "You declined the Sponsorship Invitation. No Sponsorship, reporting access, or Class Credit grant was created.",
    "sponsorship-invitation.declined.manager": "{studentDisplayName} declined the Sponsorship Invitation. No Sponsorship or reporting access was created.",
    "sponsorship-invitation.expired.student": "Your Sponsorship Invitation from {organizationName} expired without a response. No Sponsorship, reporting access, or Class Credit grant was created.",
    "sponsorship-invitation.expired.manager": "The Sponsorship Invitation to {studentDisplayName} expired without a response. No Sponsorship or reporting access was created.",
    "organization-credit.granted.student": "Organization Credit Benefit granted {amount, number} Class Credits. Available balance: {availableBalance, number}. Next grant: {nextAnniversaryAt, date, long} at {nextAnniversaryAt, time, short}.",
    "sponsorship.studentTitle": "My Sponsorship",
    "sponsorship.loading": "Loading Sponsorship…",
    "sponsorship.loadError": "We couldn't load your Sponsorship. Try again.",
    "sponsorship.none": "No Organization currently sponsors you.",
    "sponsorship.organization": "Organization: {name}",
    "sponsorship.acceptedAt": "Sponsored since {date}",
    "sponsorship.nextAnniversary": "Next Organization credit grant: {date}",
    "sponsorship.invitations.title": "Sponsorship Invitations",
    "sponsorship.invitations.empty": "You have no Sponsorship Invitations.",
    "sponsorship.invitations.state.PENDING": "Awaiting your decision",
    "sponsorship.invitations.state.ACCEPTED": "Accepted",
    "sponsorship.invitations.state.DECLINED": "Declined",
    "sponsorship.invitations.state.EXPIRED": "Expired",
    "sponsorship.invitations.expiresAt": "Expires {date}",
    "sponsorship.invitations.decidedAt": "Decided {date}",
    "sponsorship.invitations.disclosure.title": "Disclosure (version {version})",
    "sponsorship.invitations.disclosure.benefit": "Benefit: {description}",
    "sponsorship.invitations.disclosure.visibleData": "Organization sees: {description}",
    "sponsorship.invitations.disclosure.excludedData": "Never shared: {description}",
    "sponsorship.invitations.accept": "Accept",
    "sponsorship.invitations.decline": "Decline",
    "sponsorship.invitations.accepted": "Sponsorship accepted.",
    "sponsorship.invitations.declined": "Invitation declined.",
    "sponsorship.invitations.responseError": "We couldn't record your decision. Try again with the same request.",
    "sponsorship.invite.title": "Invite a Student to Sponsorship",
    "sponsorship.invite.studentUserId": "Student User ID",
    "sponsorship.invite.submit": "Send Sponsorship Invitation",
    "sponsorship.invite.sent": "Sponsorship Invitation sent.",
    "sponsorship.invite.error": "We couldn't send that Sponsorship Invitation. Review the Student User ID and try again.",
    "sponsorship.invite.notFound": "Choose a User with a Student Role Assignment.",
    "sponsorship.invite.alreadySponsored": "The Student already has a Sponsorship.",
    "sponsorship.invite.alreadyPending": "The Student already has a pending Sponsorship Invitation from your Organization.",
    "sponsorship.sentInvitations.title": "Sent Sponsorship Invitations",
    "sponsorship.sentInvitations.empty": "Your Organization has not sent any Sponsorship Invitations.",
    "sponsorship.sponsoredStudents.title": "Sponsored Students",
    "sponsorship.sponsoredStudents.empty": "Your Organization does not currently sponsor any Students.",
    "sponsorship.student": "Student: {name}",
    "curriculum.loading": "Loading curriculum administration…",
    "curriculum.error": "We couldn't update the curriculum. Review the details and try again.",
    "curriculum.sampleBadge": "Sample curriculum",
    "curriculum.title": "Curriculum administration",
    "curriculum.notice": "Illustrative, incomplete curriculum for this public demonstration; it is not a formally certified language program.",
    "curriculum.catalog": "Courses and Lesson Units",
    "curriculum.empty": "No Courses have been created yet.",
    "curriculum.active": "Active",
    "curriculum.retired": "Retired",
    "curriculum.retire": "Retire Lesson Unit",
    "curriculum.newCourse": "Create a Course",
    "curriculum.targetLanguage": "Target language code",
    "curriculum.level": "Curriculum Level",
    "curriculum.courseTitle": "Course title",
    "curriculum.summary": "Summary",
    "curriculum.createCourse": "Create Course",
    "curriculum.courseCreated": "Course created.",
    "curriculum.editCourse": "Edit Course details",
    "curriculum.saveCourse": "Save Course",
    "curriculum.courseUpdated": "Course updated.",
    "curriculum.newUnit": "Add a Lesson Unit",
    "curriculum.course": "Course",
    "curriculum.unitTitle": "Lesson Unit title",
    "curriculum.objectives": "Objectives",
    "curriculum.objectivesHelp": "Enter one objective per line.",
    "curriculum.topics": "Topics",
    "curriculum.createUnit": "Create Lesson Unit",
    "curriculum.unitCreated": "Lesson Unit created.",
    "curriculum.unitRetired": "Lesson Unit retired; its history remains available.",
    "curriculum.editUnit": "Edit Lesson Unit",
    "curriculum.saveUnit": "Save Lesson Unit",
    "curriculum.unitUpdated": "Lesson Unit updated.",
    "curriculum.identityLocked": "Instructional identity is locked because this Lesson Unit has been published.",
    "curriculum.moveUp": "Move up",
    "curriculum.moveDown": "Move down",
    "curriculum.unitReordered": "Lesson Unit order updated.",
    "curriculum.replacement": "Replacement Lesson Unit",
    "curriculum.noReplacement": "No replacement",
    "curriculum.manageTopic": "Manage a localized Topic",
    "curriculum.topicKey": "Topic key",
    "curriculum.labelEn": "English label",
    "curriculum.labelEs": "Spanish label",
    "curriculum.saveTopic": "Save Topic",
    "curriculum.topicSaved": "Topic saved in English and Spanish.",
    "curriculum.addMaterial": "Add Lesson Material",
    "curriculum.unit": "Lesson Unit",
    "curriculum.materialKind": "Material form",
    "curriculum.structuredText": "Structured text",
    "curriculum.httpsReference": "HTTPS reference",
    "curriculum.materialTitle": "Material title",
    "curriculum.materialHeading": "Structured heading",
    "curriculum.materialBody": "Structured paragraph",
    "curriculum.materialList": "Structured list (one item per line)",
    "curriculum.materialEmphasis": "Structured emphasis",
    "curriculum.httpsUrl": "HTTPS URL",
    "curriculum.publisher": "Publisher",
    "curriculum.addMaterialAction": "Add Lesson Material",
    "curriculum.materialAdded": "Lesson Material added.",
    "curriculum.reviseMaterial": "Revise a Lesson Material",
    "curriculum.reviseMaterialAction": "Save Lesson Material revision",
    "curriculum.materialRevised": "Lesson Material revised.",
    "curriculum.teacherProfile": "Manage a Teacher Profile",
    "curriculum.teacherUserId": "Teacher User ID",
    "curriculum.pronouns": "Pronouns",
    "curriculum.profileImageUrl": "Profile image HTTPS URL",
    "curriculum.biography": "Professional biography",
    "curriculum.teachingTopics": "Teaching Topics",
    "curriculum.saveProfile": "Save Teacher Profile",
    "curriculum.profileSaved": "Teacher Profile saved.",
    "curriculum.teacherQualification": "Manage a Teacher Qualification",
    "curriculum.action": "Action",
    "curriculum.grant": "Grant",
    "curriculum.remove": "Remove",
    "curriculum.applyQualification": "Apply Teacher Qualification change",
    "curriculum.qualificationGranted": "Teacher Qualification granted and the Teacher was notified.",
    "curriculum.qualificationRemoved": "Teacher Qualification removed and the Teacher was notified.",
    "curriculum.qualificationBlocked": "Resolve the listed future Class Sessions before removing this Teacher Qualification.",
    "curriculum.teachers": "Teacher Profiles and Qualifications",
    "curriculum.teacherId": "Teacher User ID",
    "teacher-qualification.granted.teacher": "Teacher Qualification granted for {targetLanguage} {curriculumLevel} on {effectiveTime, date, long} at {effectiveTime, time, short}.",
    "teacher-qualification.removed.teacher": "Teacher Qualification removed for {targetLanguage} {curriculumLevel} on {effectiveTime, date, long} at {effectiveTime, time, short}.",
    "class-session.teacher-assigned.teacher": "{imminent, select, true {Imminent assignment: } other {}}You are assigned to Class Session {classSessionId} on {startsAt, date, long} at {startsAt, time, short}.",
    "class-session.reminder.teacher": "Reminder: Class Session {classSessionId} starts on {startsAt, date, long} at {startsAt, time, short}.",
    "class-session.reminder.student": "Reminder: Class Session {classSessionId} starts on {startsAt, date, long} at {startsAt, time, short}.",
    "absence-request.created.administrator": "Teacher {teacherUserId} reported an absence affecting Class Sessions {classSessionIds}. Resolve the commitments: {resolutionLink}",
    "class-session.teacher-removed.teacher": "You are no longer assigned to Class Session {classSessionId} on {startsAt, date, long} at {startsAt, time, short}.",
    "class-session.teacher-substituted.teacher": "{imminent, select, true {Imminent assignment: } other {}}You are the replacement Teacher for Class Session {classSessionId} on {startsAt, date, long} at {startsAt, time, short}.",
    "class-session.teacher-substituted.student": "Class Session {classSessionId} on {startsAt, date, long} at {startsAt, time, short} will be led by replacement Teacher {replacementTeacherDisplayName}. You may cancel and receive one Class Credit back.",
    "class-session.cancelled.student": "Class Session {classSessionId} on {startsAt, date, long} at {startsAt, time, short} was cancelled. One Class Credit was returned.",
    "class-session.cancelled.teacher": "Class Session {classSessionId} on {startsAt, date, long} at {startsAt, time, short} was cancelled.",
    "booking.created.student": "Booking confirmed for Class Session {classSessionId} on {startsAt, date, long} at {startsAt, time, short}. One Class Credit was exchanged; {availableBalance, plural, one {# remains} other {# remain}}.",
    "booking.cancelled.student": "Booking cancelled for Class Session {classSessionId}. {classCreditRefunded, select, true {One Class Credit was returned.} other {The Class Credit was forfeited under the late-cancellation rule.}} Available balance: {availableBalance, number}.",
    "booking.rescheduled.student": "Booking moved from Class Session {originalClassSessionId} to Class Session {replacementClassSessionId} on {startsAt, date, long} at {startsAt, time, short}. The same Class Credit was retained.",
    "waitlist-entry.created.student": "Waitlist joined for Class Session {classSessionId} until {expiresAt, date, long} at {expiresAt, time, short}. No seat or Class Credit is reserved; promotion may automatically exchange one Class Credit.",
    "waitlist-entry.withdrawn.student": "Waitlist withdrawn for Class Session {classSessionId}. Automatic promotion stopped; no Booking was created and no Class Credit was exchanged.",
    "waitlist-entry.promoted.student": "{imminent, select, true {Starting soon: } other {}}Waitlist promotion confirmed Booking {bookingId} for Class Session {classSessionId} on {startsAt, date, long} at {startsAt, time, short}. One Class Credit was exchanged. You may cancel for a refund until {refundUntil, time, short}.",
    "waitlist-entry.ineligible.student": "Waitlist promotion ended for Class Session {classSessionId}: {reasonCode, select, INSUFFICIENT_CLASS_CREDITS {an available Class Credit is no longer available} SCHEDULE_CONFLICT {another commitment now overlaps this Class Session} ALREADY_BOOKED {an active Booking already exists} CLASS_SESSION_UNAVAILABLE {the Class Session is no longer available} other {eligibility changed}}. No Booking was created or Class Credit exchanged.",
    "waitlist-entry.expired.student": "Waitlist Entry expired for Class Session {classSessionId}. No Booking was created or Class Credit exchanged.",
    "classSession.loading": "Loading Class Session administration…",
    "classSession.loadError": "We couldn't load Class Session administration. Try again.",
    "classSession.title": "Class Session administration",
    "classSession.publish": "Publish a Class Session",
    "classSession.lessonUnit": "Lesson Unit",
    "classSession.teacher": "Teacher",
    "classSession.localStart": "Local start time",
    "classSession.schedulingTimeZone": "Scheduling time zone",
    "classSession.disambiguation": "Repeated local time",
    "classSession.disambiguation.reject": "Require an unambiguous time",
    "classSession.disambiguation.earlier": "Earlier occurrence",
    "classSession.disambiguation.later": "Later occurrence",
    "classSession.seatCapacity": "Seat Capacity",
    "classSession.publishAction": "Publish Class Session",
    "classSession.published": "Class Session published for 60 minutes with Seat Capacity {seatCapacity}.",
    "classSession.current": "Published Class Sessions",
    "classSession.resolveAbsences": "Resolve Absence Requests",
    "classSession.noAbsences": "There are no open Absence Requests.",
    "classSession.absenceRequest": "Absence Request",
    "classSession.cancellationReason": "Cancellation reason",
    "classSession.cancelAction": "Cancel Class Session",
    "classSession.replacementTeacher": "Replacement Teacher",
    "classSession.substituteAction": "Substitute Teacher",
    "classSession.cancelled": "Class Session cancelled; {bookings, plural, one {# Booking refunded} other {# Bookings refunded}} and {waitlist, plural, one {# Waitlist Entry removed} other {# Waitlist Entries removed}}.",
    "classSession.substituted": "Replacement Teacher assigned without changing the Class Session start time.",
    "classSession.none": "No Class Sessions have been published.",
    "classSession.capacityAction": "Change Seat Capacity",
    "classSession.capacityChanged": "Seat Capacity changed to {seatCapacity}.",
    "classSession.error": "We couldn't save the Class Session change. Review the details and try again.",
    "classSession.error.invalidSeatCapacity": "Seat Capacity must be from 2 through 8.",
    "classSession.error.invalidTimeZone": "Choose a named regional scheduling time zone.",
    "classSession.error.fold": "Choose the earlier or later occurrence of the repeated local time.",
    "classSession.error.gap": "That local time does not exist because of a daylight-saving transition.",
    "classSession.error.invalidLocalDateTime": "Enter a valid local Class Session start time.",
    "classSession.error.invalidLessonUnit": "Choose an active Lesson Unit.",
    "classSession.error.qualificationRequired": "The Teacher needs a matching Teacher Qualification.",
    "classSession.error.availabilityRequired": "The full Class Session must fit within compatible Teacher Availability.",
    "classSession.error.availabilityException": "An Availability Exception overlaps this Class Session.",
    "classSession.error.scheduleConflict": "The Teacher already has an overlapping Class Session.",
    "classSession.error.notFound": "Choose a published Class Session.",
    "classSession.error.capacityBelowOccupied": "Seat Capacity cannot be lower than the occupied seats.",
    "classSession.error.idempotencyKeyReused": "That request identifier was already used for a different change.",
    "classSession.error.attendanceSubmitted": "This Class Session cannot be cancelled after an Attendance Record was submitted.",
    "attendance.published.student": "Attendance for Class Session {classSessionId}: {outcome, select, ATTENDED {Attended} other {No-show}}. Request a review by {reviewDeadline, date, long} at {reviewDeadline, time, short}.{outcome, select, ATTENDED { Submit a Session Rating by {ratingDeadline, date, long} at {ratingDeadline, time, short}.} other {}}",
    "attendance.corrected.student": "Attendance for Class Session {classSessionId} was corrected to {outcome, select, ATTENDED {Attended} other {No-show}}.",
    "attendance.corrected.teacher": "Attendance for Class Session {classSessionId} was corrected by a Platform Administrator to {outcome, select, ATTENDED {Attended} other {No-show}}.",
    "attendance.loading": "Loading Attendance work…",
    "attendance.loadError": "We couldn't load Attendance work. Try again.",
    "attendance.title": "Record Attendance",
    "attendance.none": "No Class Sessions are currently open for Attendance recording.",
    "attendance.openRoster": "Record Attendance for {startsAt}",
    "attendance.rosterLoading": "Loading the Class Roster…",
    "attendance.attended": "Attended",
    "attendance.noShow": "No-show",
    "attendance.submit": "Publish Attendance",
    "attendance.published": "Attendance was published.",
    "attendance.error": "We couldn't publish Attendance. Review the Class Roster and try again.",
    "attendance.correctionReason": "Correction reason",
    "attendance.error.correctionReason": "Give a correction reason of at least 10 characters.",
    "attendance.error.notOpen": "Attendance remains Unrecorded until the Class Session ends.",
    "attendance.error.windowClosed": "The Teacher Attendance recording window has closed.",
    "attendance.error.rosterMismatch": "Reload the Class Roster before publishing Attendance.",
    "attendance.error.notFound": "This Class Session is not available for Attendance recording.",
    "attendance.error.idempotency": "This request identifier was already used for different Attendance input.",
    "learning-feedback.submitted.student": "Learning Feedback is available for Class Session {classSessionId}.",
    "feedback.title": "Learning Feedback",
    "feedback.studentTitle": "Feedback and Session Ratings",
    "feedback.loading": "Loading feedback…",
    "feedback.loadError": "We couldn't load feedback. Try again.",
    "feedback.empty": "There are no Attended Bookings open for Learning Feedback.",
    "feedback.studentEmpty": "There are no Attended Class Sessions to review yet.",
    "feedback.notSubmitted": "Learning Feedback has not been submitted.",
    "feedback.deadline": "Submit or revise by {deadline}.",
    "feedback.strengths": "Observed strengths (up to three)",
    "feedback.focuses": "Suggested focus (up to three)",
    "feedback.observations": "Observations",
    "feedback.nextPractice": "Next practice",
    "feedback.saveDraft": "Save private draft",
    "feedback.submit": "Submit Learning Feedback",
    "feedback.revise": "Revise Learning Feedback",
    "feedback.saved": "Learning Feedback saved.",
    "feedback.error": "We couldn't save Learning Feedback. Review the content and deadline.",
    "feedback.skill.LISTENING": "Listening",
    "feedback.skill.READING": "Reading",
    "feedback.skill.SPOKEN_INTERACTION": "Spoken interaction",
    "feedback.skill.SPOKEN_PRODUCTION": "Spoken production",
    "feedback.skill.WRITING": "Writing",
    "feedback.skill.VOCABULARY": "Vocabulary",
    "feedback.skill.GRAMMAR": "Grammar",
    "feedback.skill.PRONUNCIATION": "Pronunciation",
    "rating.deadline": "Submit or edit your private Session Rating by {deadline}.",
    "rating.overall": "Overall Session Rating",
    "rating.positiveTags": "What worked well",
    "rating.improvementTags": "What could improve",
    "rating.comment": "Private comment for Platform Administrators",
    "rating.submit": "Submit Session Rating",
    "rating.edit": "Save edited Session Rating",
    "rating.saved": "Session Rating saved privately.",
    "rating.error": "We couldn't save your Session Rating. Review the rating and deadline.",
    "rating.closed": "The Session Rating editing window has closed.",
    "rating.tag.CLEAR_EXPLANATIONS": "Clear explanations",
    "rating.tag.SUPPORTIVE": "Supportive",
    "rating.tag.ENGAGING": "Engaging",
    "rating.tag.USEFUL_PRACTICE": "Useful practice",
    "rating.tag.PACING": "Pacing",
    "rating.tag.AUDIO_QUALITY": "Audio quality",
    "rating.tag.MORE_CORRECTION": "More correction",
    "rating.tag.MORE_SPEAKING_TIME": "More speaking time",
    "quality.title": "Learning quality",
    "quality.loading": "Loading private quality records…",
    "quality.error": "We couldn't load private quality records. Try again.",
    "quality.empty": "There are no private feedback or rating records.",
    "quality.feedbackState": "Learning Feedback state: {state}",
    "quality.feedbackState.DRAFT": "Private draft",
    "quality.feedbackState.SUBMITTED": "Submitted",
    "quality.rating": "Session Rating: {rating} of 5.",
    "progress.loading": "Loading Course Progress…",
    "progress.loadError": "We couldn't load Course Progress. Try again.",
    "progress.title": "Course Progress",
    "progress.none": "No Course Progress is available yet.",
    "progress.label": "{course} progress",
    "progress.summary": "{completed} of {total} active Lesson Units completed",
    "progress.history": "Learning history",
    "progress.activeHistory": "{title} — counts toward progress",
    "progress.retiredHistory": "{title} — retired history",
    "classSession.error.disruptionResolved": "This Class Session disruption was already resolved and cannot be changed.",
    "classSession.error.invalidReason": "Provide a cancellation reason from 10 through 500 characters.",
    "classSession.error.replacementRequired": "Choose a different Teacher as the replacement.",
    "classSession.error.alreadyStarted": "This disruption can no longer be resolved because the Class Session has started.",
    "auth.loading": "Checking your session…",
    "auth.error": "We couldn't verify your session. Try again.",
    "auth.signIn": "Sign in",
    "teacherSchedule.loading": "Loading assigned Class Sessions…",
    "teacherSchedule.loadError": "We couldn't load your assigned Class Sessions. Try again.",
    "teacherSchedule.title": "Assigned Class Sessions",
    "teacherSchedule.help": "Reporting an Absence Request leaves each published Class Session and Booking intact until a Platform Administrator resolves it.",
    "teacherSchedule.none": "You have no upcoming assigned Class Sessions.",
    "teacherSchedule.choose": "Choose Class Sessions you cannot lead",
    "teacherSchedule.report": "Report absence",
    "teacherSchedule.absenceReported": "The Absence Request was submitted for Platform Administrator resolution.",
    "teacherSchedule.error": "We couldn't submit the Absence Request. Review the selected Class Sessions and try again.",
    "teacherSchedule.requests": "Absence Requests",
    "teacherSchedule.noRequests": "You have no Absence Requests.",
    "teacherSchedule.requestOpen": "Open Absence Request affecting {count, plural, one {# Class Session} other {# Class Sessions}}.",
    "teacherSchedule.requestResolved": "Resolved Absence Request affecting {count, plural, one {# Class Session} other {# Class Sessions}}.",
    "learningAccess.loading": "Loading Lesson Materials and classroom access…",
    "learningAccess.loadError": "We couldn't load Lesson Materials and classroom access. Try again.",
    "learningAccess.title": "Lesson Materials and classroom",
    "learningAccess.help": "Lesson Materials follow your Booking, completion, or teaching assignment. Classroom entry is available only around the Class Session time.",
    "learningAccess.none": "No Class Sessions currently provide learning access.",
    "learningAccess.openMaterials": "Open Lesson Materials",
    "learningAccess.enterClassroom": "Enter classroom",
    "learningAccess.materials": "Lesson Materials",
    "learningAccess.classroom": "Classroom Access",
    "learningAccess.noMaterials": "This Lesson Unit has no Lesson Materials.",
    "learningAccess.classroomReady": "Simulated classroom ready. Entry does not record Attendance.",
    "learningAccess.error": "That learning access is not available right now. Check your relationship and the Class Session time.",
    "availability.loading": "Loading Teacher Availability…",
    "availability.loadError": "We couldn't load Teacher Availability. Try again.",
    "availability.title": "Weekly Teacher Availability",
    "availability.timeZone": "Teacher time zone: {timeZone}",
    "availability.dstHelp": "Weekly hours stay at these wall-clock times when daylight-saving offsets change. Future effective dates preserve earlier scheduling context.",
    "availability.weekday": "Weekday",
    "availability.startTime": "Start time",
    "availability.endTime": "End time",
    "availability.effectiveFrom": "Effective from",
    "availability.addRange": "Add weekly range",
    "availability.effectiveUntil": "Effective until",
    "availability.endRange": "End weekly range",
    "availability.rangeSaved": "Weekly Teacher Availability saved.",
    "availability.rangeDescription": "{weekday}, {start}–{end} from {from}",
    "availability.rangeDescriptionEnded": "{weekday}, {start}–{end} from {from} through {until}",
    "availability.ranges": "Saved weekly ranges",
    "availability.exceptions": "Availability Exceptions",
    "availability.unavailableFrom": "Unavailable from",
    "availability.unavailableUntil": "Unavailable until",
    "availability.repeatedStart": "Repeated start time",
    "availability.repeatedEnd": "Repeated end time",
    "availability.addException": "Add Availability Exception",
    "availability.exceptionSaved": "Availability Exception saved.",
    "availability.exceptionDescription": "{start}–{end}",
    "availability.savedExceptions": "Saved Availability Exceptions",
    "availability.removeException": "Remove Availability Exception",
    "availability.createAbsenceRequest": "Create an Absence Request",
    "availability.saveError": "We couldn't save that change. Review the details and try again.",
    "availability.disambiguation.reject": "Require an unambiguous time",
    "availability.disambiguation.earlier": "Earlier occurrence",
    "availability.disambiguation.later": "Later occurrence",
    "availability.error.exceptionNotFound": "The Availability Exception was not found.",
    "availability.error.idempotencyKeyReused": "That request identifier was already used for a different change.",
    "availability.error.invalidRange": "Enter an end time after the start time and a valid effective date.",
    "availability.error.invalidEffectiveDate": "Choose an effective date that does not overlap a later weekly range.",
    "availability.error.invalidLocalDateTime": "Enter valid local start and end date-times.",
    "availability.error.invalidTimeRange": "The unavailable-until time must be after the unavailable-from time.",
    "availability.error.invalidTimeZone": "Choose a named regional time zone.",
    "availability.error.fold": "Choose the earlier or later occurrence of the repeated local time.",
    "availability.error.gap": "That local time does not exist because of a daylight-saving transition.",
    "availability.error.sessionOverlap": "A published Class Session occupies this time. Create an Absence Request instead.",
    "discovery.title": "Discover Class Sessions",
    "discovery.filters": "Discovery filters",
    "discovery.targetLanguage": "Target language",
    "discovery.curriculumLevel": "Curriculum Level",
    "discovery.anyLevel": "Any Curriculum Level",
    "discovery.teacher": "Teacher",
    "discovery.anyTeacher": "Any Teacher",
    "discovery.topics": "Topics (match any)",
    "discovery.localDate": "Local date",
    "discovery.localDateHelp": "Leave blank to search the next seven dates in {timeZone}.",
    "discovery.search": "Search Class Sessions",
    "discovery.savePlacement": "Save Student Placement",
    "discovery.placementSaved": "Student Placement saved.",
    "discovery.loading": "Finding Class Sessions…",
    "discovery.error": "We couldn't load Class Session Discovery. Try again.",
    "discovery.none": "No actionable Class Sessions match these filters.",
    "discovery.results": "Class Session results",
    "discovery.seatsAvailable": "{occupied} of {total} seats occupied; seats available",
    "discovery.waitlistOpen": "{occupied} of {total} seats occupied; Waitlist open",
    "discovery.teacherProfile": "Teacher Profile",
    "discovery.completedSessions": "{count, plural, one {# completed Class Session} other {# completed Class Sessions}}",
    "discovery.taughtLanguages": "Taught languages: {languages}",
    "discovery.qualifiedLevels": "Qualified Curriculum Levels: {levels}",
    "discovery.teachingTopics": "Teaching Topics: {topics}",
    "discovery.objectives": "Objectives",
    "discovery.loadMore": "Load more Class Sessions",
    "booking.bookAction": "Book Class Session",
    "booking.cancelAction": "Cancel Booking",
    "booking.rescheduleAction": "Reschedule Booking",
    "booking.activeTitle": "My active Bookings",
    "booking.active": "Booking active",
    "booking.cancelFor": "Cancel Booking for {startsAt, date, long} at {startsAt, time, short}",
    "booking.rescheduleFromTo": "Reschedule Booking from {originalStartsAt, date, long} at {originalStartsAt, time, short} to {replacementStartsAt, date, long} at {replacementStartsAt, time, short}",
    "booking.booking": "Booking Class Session…",
    "booking.cancelling": "Cancelling Booking…",
    "booking.rescheduling": "Rescheduling Booking…",
    "booking.created": "Booking confirmed. One Class Credit was exchanged.",
    "booking.cancelled.refunded": "Booking cancelled. One Class Credit was returned.",
    "booking.cancelled.forfeited": "Booking cancelled. The Class Credit was forfeited under the late-cancellation rule.",
    "booking.rescheduled": "Booking rescheduled. The same Class Credit was retained.",
    "booking.error": "We couldn't complete the Booking change. Review the details and try again.",
    "booking.error.CLASS_SESSION_NOT_FOUND": "This Class Session is no longer available.",
    "booking.error.BOOKING_WINDOW_CLOSED": "Booking closes 30 minutes before the Class Session starts.",
    "booking.error.SESSION_FULL": "This Class Session is full.",
    "booking.error.INSUFFICIENT_CLASS_CREDITS": "One available Class Credit is required to book.",
    "booking.error.SCHEDULE_CONFLICT": "This Class Session overlaps another active Student or Teacher commitment.",
    "booking.error.ALREADY_BOOKED": "You already have an active Booking for this Class Session.",
    "booking.error.BOOKING_NOT_FOUND": "This Booking is no longer available.",
    "booking.error.BOOKING_NOT_ACTIVE": "Only an active Booking can be cancelled.",
    "booking.error.CANCELLATION_WINDOW_CLOSED": "A Booking cannot be cancelled after its Class Session starts.",
    "booking.error.LESSON_UNIT_MISMATCH": "Choose a replacement Class Session delivering the same Lesson Unit.",
    "booking.error.IDEMPOTENCY_KEY_REUSED": "That request identifier was already used for a different Booking change.",
    "waitlist.joinAction": "Join Waitlist",
    "waitlist.joining": "Joining Waitlist…",
    "waitlist.withdrawAction": "Withdraw from Waitlist",
    "waitlist.withdrawing": "Withdrawing from Waitlist…",
    "waitlist.withdrawFor": "Withdraw from Waitlist for {startsAt, date, long} at {startsAt, time, short}",
    "waitlist.active": "Waitlist Entry active",
    "waitlist.joined": "Waitlist joined. No seat or Class Credit is reserved.",
    "waitlist.withdrawn": "Waitlist withdrawn. No Booking was created or Class Credit exchanged.",
    "waitlist.promotionWon": "Promotion completed first. Your Booking is active; cancel it if you no longer want the seat.",
    "waitlist.error": "We couldn't complete the Waitlist change. Review the details and try again.",
    "waitlist.error.CLASS_SESSION_NOT_FOUND": "This Class Session is no longer available.",
    "waitlist.error.WAITLIST_NOT_OPEN": "The Waitlist closes two hours before the Class Session starts.",
    "waitlist.error.SESSION_NOT_FULL": "This Class Session has an available seat; book it instead.",
    "waitlist.error.INSUFFICIENT_CLASS_CREDITS": "One available Class Credit is required to join the Waitlist.",
    "waitlist.error.SCHEDULE_CONFLICT": "This Class Session overlaps another active Student or Teacher commitment.",
    "waitlist.error.ALREADY_BOOKED": "You already have an active Booking for this Class Session.",
    "waitlist.error.ALREADY_WAITLISTED": "You already have an active Waitlist Entry for this Class Session.",
    "waitlist.error.WAITLIST_ENTRY_NOT_FOUND": "This Waitlist Entry is no longer available.",
    "waitlist.error.WAITLIST_ENTRY_NOT_ACTIVE": "Only an active Waitlist Entry can be withdrawn.",
    "waitlist.error.IDEMPOTENCY_KEY_REUSED": "That request identifier was already used for a different Waitlist change.",
  },
  es: {
    "workspace.eyebrow": "Espacio de estudiante",
    "workspace.greeting": "Hola, {name}",
    "workspace.introduction": "Tu recorrido de aprendizaje comienza aquí.",
    "workspace.timeZone": "Zona horaria: {timeZone}",
    "workspace.settings": "Configuración",
    "notifications.title": "Notificaciones",
    "notifications.loading": "Cargando notificaciones…",
    "notifications.error": "No pudimos cargar tus notificaciones. Inténtalo de nuevo.",
    "notifications.empty": "No tienes notificaciones.",
    "notifications.markRead": "Marcar como leída",
    "notifications.read": "Leída",
    "administratorTasks.title": "Tareas de administración",
    "administratorTasks.loading": "Cargando tareas de administración…",
    "administratorTasks.error": "No pudimos cargar las tareas de administración. Inténtalo de nuevo.",
    "administratorTasks.empty": "No hay trabajo de administración pendiente.",
    "administratorTasks.notificationDelivery": "Conciliar una entrega de notificación agotada.",
    "administratorTasks.correlation": "Referencia de correlación",
    "administratorTasks.channel": "Canal",
    "administratorTasks.message": "Política de mensajes",
    "administratorTasks.reason": "Motivo de resolución",
    "administratorTasks.resolve": "Resolver tarea",
    "administratorTasks.resolved": "Tarea resuelta.",
    "workspace.navigation": "Navegación del espacio",
    "workspace.actingRole": "Rol activo",
    "workspace.relationshipScope": "Alcance: {scope}",
    "workspace.mobileDrawer": "Menú de recorridos",
    "workspace.deepLink.eyebrow": "Cambio de espacio",
    "workspace.deepLink.heading": "¿Cambiar al espacio de {role}?",
    "workspace.deepLink.explanation": "Seguir este enlace no cambiará tu rol activo. Elige el cambio de rol explícitamente o vuelve de forma segura a tu espacio actual.",
    "workspace.deepLink.change": "Cambiar a {role}",
    "workspace.deepLink.return": "Volver a {role}",
    "role.student": "estudiante",
    "role.teacher": "docente",
    "role.organizationManager": "responsable de organización",
    "role.platformAdministrator": "administración de la plataforma",
    "workspace.student": "Espacio de estudiante",
    "workspace.teacher": "Espacio de docente",
    "workspace.organizationManager": "Espacio de responsable de organización",
    "workspace.platformAdministrator": "Espacio de administración de la plataforma",
    "workspace.scope.student": "Tu propio aprendizaje",
    "workspace.scope.teacher": "Sesiones de clase asignadas",
    "workspace.scope.organizationManager": "Organización asignada",
    "workspace.scope.platformAdministrator": "Todo el mercado",
    "workspace.journey.student.discovery": "Descubrir sesiones de clase",
    "workspace.journey.student.learning": "Mi aprendizaje",
    "workspace.journey.teacher.schedule": "Horario docente",
    "workspace.journey.teacher.availability": "Disponibilidad",
    "workspace.journey.organization.students": "Estudiantes patrocinados",
    "workspace.journey.organization.reports": "Informes",
    "workspace.journey.administration.operations": "Operaciones del mercado",
    "workspace.journey.administration.people": "Personas",
    "workspace.place.student.discovery": "Encuentra tu próxima sesión de clase.",
    "workspace.place.student.learning": "Revisa tu recorrido de aprendizaje.",
    "workspace.place.teacher.schedule": "Revisa tus sesiones de clase asignadas.",
    "workspace.place.teacher.availability": "Gestiona cuándo estás disponible para enseñar.",
    "workspace.place.organization.students": "Revisa a los estudiantes de tu organización asignada.",
    "workspace.place.organization.reports": "Abre informes de patrocinio con privacidad limitada.",
    "workspace.place.administration.operations": "Revisa las operaciones del mercado.",
    "workspace.place.administration.people": "Gestiona usuarios y asignaciones de rol.",
    "workspace.loading": "Abriendo tu espacio…",
    "workspace.error": "No pudimos abrir tu espacio. Inténtalo de nuevo.",
    "workspace.safeReturn": "Volver de forma segura",
    "preferences.title": "Elige tus preferencias",
    "preferences.savedTitle": "Tus preferencias",
    "preferences.suggestion": "Estas opciones son sugerencias de este navegador. No se guardan hasta que des tu consentimiento.",
    "preferences.locale": "Idioma de la interfaz",
    "preferences.locale.en": "Inglés",
    "preferences.locale.es": "Español",
    "preferences.timeZone": "Zona horaria de visualización",
    "preferences.timeZoneHelp": "Las horas de las sesiones de clase y las fechas del calendario usan esta zona horaria regional.",
    "preferences.save": "Guardar preferencias",
    "preferences.saving": "Guardando preferencias…",
    "preferences.saved": "Preferencias guardadas.",
    "preferences.error": "No pudimos guardar tus preferencias. Inténtalo de nuevo.",
    "workspace.timeZonePreview": "Vista previa de la zona horaria",
    "workspace.currentInstant": "Hora local cuando se abrió esta página: {instant}",
    "workspace.localDate": "Fecha del calendario",
    "workspace.localDateHelp": "Esta fecha comienza a las {instant} en tiempo universal cuando se interpreta en tu zona horaria de visualización.",
    "workspace.localDateInvalid": "Esa fecha del calendario no tiene un comienzo inequívoco en esta zona horaria de visualización.",
    "credit-adjustment.committed.student": "Ajuste de créditos de clase: {amount, number, ::sign-always} créditos. Saldo disponible: {availableBalance, number}. Motivo: {reason}",
    "subscription.activated.student": "Suscripción activada con {amount, number} créditos de clase. Saldo disponible: {availableBalance, number}. Próxima concesión: {nextAnniversaryAt, date, long} a las {nextAnniversaryAt, time, short}.",
    "subscription.renewed.student": "Suscripción renovada con {amount, number} créditos de clase. Saldo disponible: {availableBalance, number}. Próxima concesión: {nextAnniversaryAt, date, long} a las {nextAnniversaryAt, time, short}.",
    "subscription.cancellation-scheduled.student": "La cancelación de la suscripción está programada para {cancellationEffectiveAt, date, long} a las {cancellationEffectiveAt, time, short}. No se concederán créditos entonces y conservarás tus créditos de clase existentes.",
    "subscription.cancellation-undone.student": "Se anuló la cancelación de la suscripción. No se concedieron créditos de clase de inmediato. La próxima concesión sigue programada para {nextAnniversaryAt, date, long} a las {nextAnniversaryAt, time, short}.",
    "classCredits.studentTitle": "Mis créditos de clase",
    "classCredits.adminTitle": "Administración de créditos de clase",
    "classCredits.studentUserId": "ID de usuario estudiante",
    "classCredits.inspect": "Consultar créditos de clase",
    "classCredits.loading": "Cargando créditos de clase…",
    "classCredits.loadError": "No pudimos cargar los créditos de clase. Inténtalo de nuevo.",
    "classCredits.balance": "{balance, plural, one {# crédito de clase disponible} other {# créditos de clase disponibles}}",
    "classCredits.ledger": "Libro mayor de créditos de clase",
    "classCredits.empty": "Aún no hay actividad de créditos de clase.",
    "classCredits.amount": "Ajuste con signo",
    "classCredits.amountHelp": "Usa un número entero positivo para conceder créditos o uno negativo para reducir el saldo.",
    "classCredits.reason": "Motivo visible para el estudiante",
    "classCredits.adjust": "Aplicar ajuste de créditos",
    "classCredits.adjusted": "Se aplicó el ajuste de créditos y se notificó al estudiante.",
    "classCredits.notFound": "Elige un usuario con una asignación de rol de estudiante.",
    "classCredits.error": "No pudimos aplicar ese ajuste de créditos. Revisa el saldo disponible, el motivo y el identificador de la solicitud.",
    "classCredits.source.creditAdjustment": "Ajuste de créditos",
    "classCredits.source.subscriptionGrant": "Concesión de suscripción",
    "classCredits.source.organizationGrant": "Concesión de créditos de organización",
    "classCredits.source.bookingDeduction": "Deducción por reserva",
    "classCredits.source.bookingRefund": "Reembolso de reserva",
    "classCredits.reference": "Referencia: {reference}",
    "subscription.title": "Mi suscripción",
    "subscription.loading": "Cargando la suscripción…",
    "subscription.loadError": "No pudimos cargar tu suscripción. Inténtalo de nuevo.",
    "subscription.none": "No hay ninguna suscripción activa.",
    "subscription.state.active": "Activa",
    "subscription.state.cancellationScheduled": "Cancelación programada",
    "subscription.state.cancelled": "Cancelada",
    "subscription.nextAnniversary": "Próxima concesión de créditos de clase: {date}",
    "subscription.cancellationEffective": "La cancelación entra en vigor: {date}",
    "subscription.scheduleCancellation": "Programar cancelación",
    "subscription.keep": "Mantener la suscripción",
    "subscription.scheduled": "Cancelación programada. Conservarás tus créditos de clase existentes.",
    "subscription.undone": "Cancelación anulada. No se concedieron créditos de clase de inmediato.",
    "subscription.changeError": "No pudimos cambiar tu suscripción. Inténtalo de nuevo con la misma solicitud.",
    "sponsorship.disclosure.benefit": "Ocho créditos de clase al aceptar y ocho más en cada aniversario mensual mientras el Patrocinio permanezca activo.",
    "sponsorship.disclosure.visibleData": "Tu asistencia y progreso del curso durante el Patrocinio.",
    "sponsorship.disclosure.excludedData": "Comentarios privados de aprendizaje, calificaciones de sesión, datos de pago y tu saldo total de créditos de clase.",
    "sponsorship-invitation.created.student": "{organizationName} te invitó a un Patrocinio que ofrece ocho créditos de clase al aceptar y ocho más en cada aniversario mensual, con tu asistencia y progreso del curso visibles para la Organización durante el Patrocinio. Revisa la divulgación completa antes de decidir. Esta invitación vence el {expiresAt, date, long} a las {expiresAt, time, short}. No existe ningún Patrocinio ni acceso a informes hasta que aceptes.",
    "sponsorship-invitation.created.manager": "Invitación de Patrocinio enviada a {studentDisplayName}, vence el {expiresAt, date, long} a las {expiresAt, time, short}.",
    "sponsorship-invitation.accepted.student": "El Patrocinio con {organizationName} comenzó y otorgó {amount, number} créditos de clase. Saldo disponible: {availableBalance, number}. Próxima concesión: {nextAnniversaryAt, date, long} a las {nextAnniversaryAt, time, short}. La Organización puede ver tu asistencia y progreso del curso durante el Patrocinio. Tú o la Organización pueden finalizar el Patrocinio en cualquier momento.",
    "sponsorship-invitation.accepted.manager": "{studentDisplayName} aceptó la Invitación de Patrocinio. Los informes comienzan el {acceptedAt, date, long} a las {acceptedAt, time, short}.",
    "sponsorship-invitation.declined.student": "Rechazaste la Invitación de Patrocinio. No se creó ningún Patrocinio, acceso a informes ni concesión de créditos de clase.",
    "sponsorship-invitation.declined.manager": "{studentDisplayName} rechazó la Invitación de Patrocinio. No se creó ningún Patrocinio ni acceso a informes.",
    "sponsorship-invitation.expired.student": "Tu Invitación de Patrocinio de {organizationName} venció sin respuesta. No se creó ningún Patrocinio, acceso a informes ni concesión de créditos de clase.",
    "sponsorship-invitation.expired.manager": "La Invitación de Patrocinio a {studentDisplayName} venció sin respuesta. No se creó ningún Patrocinio ni acceso a informes.",
    "organization-credit.granted.student": "El beneficio de créditos de la Organización otorgó {amount, number} créditos de clase. Saldo disponible: {availableBalance, number}. Próxima concesión: {nextAnniversaryAt, date, long} a las {nextAnniversaryAt, time, short}.",
    "sponsorship.studentTitle": "Mi Patrocinio",
    "sponsorship.loading": "Cargando el Patrocinio…",
    "sponsorship.loadError": "No pudimos cargar tu Patrocinio. Inténtalo de nuevo.",
    "sponsorship.none": "Ninguna Organización te patrocina actualmente.",
    "sponsorship.organization": "Organización: {name}",
    "sponsorship.acceptedAt": "Patrocinado desde {date}",
    "sponsorship.nextAnniversary": "Próxima concesión de créditos de la Organización: {date}",
    "sponsorship.invitations.title": "Invitaciones de Patrocinio",
    "sponsorship.invitations.empty": "No tienes Invitaciones de Patrocinio.",
    "sponsorship.invitations.state.PENDING": "Esperando tu decisión",
    "sponsorship.invitations.state.ACCEPTED": "Aceptada",
    "sponsorship.invitations.state.DECLINED": "Rechazada",
    "sponsorship.invitations.state.EXPIRED": "Vencida",
    "sponsorship.invitations.expiresAt": "Vence el {date}",
    "sponsorship.invitations.decidedAt": "Decidida el {date}",
    "sponsorship.invitations.disclosure.title": "Divulgación (versión {version})",
    "sponsorship.invitations.disclosure.benefit": "Beneficio: {description}",
    "sponsorship.invitations.disclosure.visibleData": "La Organización ve: {description}",
    "sponsorship.invitations.disclosure.excludedData": "Nunca se comparte: {description}",
    "sponsorship.invitations.accept": "Aceptar",
    "sponsorship.invitations.decline": "Rechazar",
    "sponsorship.invitations.accepted": "Patrocinio aceptado.",
    "sponsorship.invitations.declined": "Invitación rechazada.",
    "sponsorship.invitations.responseError": "No pudimos registrar tu decisión. Inténtalo de nuevo con la misma solicitud.",
    "sponsorship.invite.title": "Invitar a un Estudiante al Patrocinio",
    "sponsorship.invite.studentUserId": "ID de usuario del Estudiante",
    "sponsorship.invite.submit": "Enviar Invitación de Patrocinio",
    "sponsorship.invite.sent": "Invitación de Patrocinio enviada.",
    "sponsorship.invite.error": "No pudimos enviar esa Invitación de Patrocinio. Revisa el ID de usuario del Estudiante e inténtalo de nuevo.",
    "sponsorship.invite.notFound": "Elige un Usuario con una asignación del rol Estudiante.",
    "sponsorship.invite.alreadySponsored": "El Estudiante ya tiene un Patrocinio.",
    "sponsorship.invite.alreadyPending": "El Estudiante ya tiene una Invitación de Patrocinio pendiente de tu Organización.",
    "sponsorship.sentInvitations.title": "Invitaciones de Patrocinio enviadas",
    "sponsorship.sentInvitations.empty": "Tu Organización no ha enviado ninguna Invitación de Patrocinio.",
    "sponsorship.sponsoredStudents.title": "Estudiantes patrocinados",
    "sponsorship.sponsoredStudents.empty": "Tu Organización no patrocina actualmente a ningún Estudiante.",
    "sponsorship.student": "Estudiante: {name}",
    "curriculum.loading": "Cargando la administración del currículo…",
    "curriculum.error": "No pudimos actualizar el currículo. Revisa los datos e inténtalo de nuevo.",
    "curriculum.sampleBadge": "Currículo de muestra",
    "curriculum.title": "Administración del currículo",
    "curriculum.notice": "Currículo ilustrativo e incompleto para esta demostración pública; no es un programa de idiomas con certificación formal.",
    "curriculum.catalog": "Cursos y unidades didácticas",
    "curriculum.empty": "Todavía no se ha creado ningún curso.",
    "curriculum.active": "Activa",
    "curriculum.retired": "Retirada",
    "curriculum.retire": "Retirar unidad didáctica",
    "curriculum.newCourse": "Crear un curso",
    "curriculum.targetLanguage": "Código del idioma objetivo",
    "curriculum.level": "Nivel curricular",
    "curriculum.courseTitle": "Título del curso",
    "curriculum.summary": "Resumen",
    "curriculum.createCourse": "Crear curso",
    "curriculum.courseCreated": "Curso creado.",
    "curriculum.editCourse": "Editar datos del curso",
    "curriculum.saveCourse": "Guardar curso",
    "curriculum.courseUpdated": "Curso actualizado.",
    "curriculum.newUnit": "Añadir una unidad didáctica",
    "curriculum.course": "Curso",
    "curriculum.unitTitle": "Título de la unidad didáctica",
    "curriculum.objectives": "Objetivos",
    "curriculum.objectivesHelp": "Escribe un objetivo por línea.",
    "curriculum.topics": "Temas",
    "curriculum.createUnit": "Crear unidad didáctica",
    "curriculum.unitCreated": "Unidad didáctica creada.",
    "curriculum.unitRetired": "Unidad didáctica retirada; su historial sigue disponible.",
    "curriculum.editUnit": "Editar unidad didáctica",
    "curriculum.saveUnit": "Guardar unidad didáctica",
    "curriculum.unitUpdated": "Unidad didáctica actualizada.",
    "curriculum.identityLocked": "La identidad didáctica está bloqueada porque esta unidad ya se publicó.",
    "curriculum.moveUp": "Subir",
    "curriculum.moveDown": "Bajar",
    "curriculum.unitReordered": "Orden de la unidad didáctica actualizado.",
    "curriculum.replacement": "Unidad didáctica de reemplazo",
    "curriculum.noReplacement": "Sin reemplazo",
    "curriculum.manageTopic": "Gestionar un tema localizado",
    "curriculum.topicKey": "Clave del tema",
    "curriculum.labelEn": "Etiqueta en inglés",
    "curriculum.labelEs": "Etiqueta en español",
    "curriculum.saveTopic": "Guardar tema",
    "curriculum.topicSaved": "Tema guardado en inglés y español.",
    "curriculum.addMaterial": "Añadir material de unidad",
    "curriculum.unit": "Unidad didáctica",
    "curriculum.materialKind": "Forma del material",
    "curriculum.structuredText": "Texto estructurado",
    "curriculum.httpsReference": "Referencia HTTPS",
    "curriculum.materialTitle": "Título del material",
    "curriculum.materialHeading": "Encabezado estructurado",
    "curriculum.materialBody": "Párrafo estructurado",
    "curriculum.materialList": "Lista estructurada (un elemento por línea)",
    "curriculum.materialEmphasis": "Énfasis estructurado",
    "curriculum.httpsUrl": "URL HTTPS",
    "curriculum.publisher": "Editorial",
    "curriculum.addMaterialAction": "Añadir material de unidad",
    "curriculum.materialAdded": "Material de unidad añadido.",
    "curriculum.reviseMaterial": "Revisar un material de unidad",
    "curriculum.reviseMaterialAction": "Guardar revisión del material",
    "curriculum.materialRevised": "Material de unidad revisado.",
    "curriculum.teacherProfile": "Gestionar un perfil docente",
    "curriculum.teacherUserId": "ID de usuario docente",
    "curriculum.pronouns": "Pronombres",
    "curriculum.profileImageUrl": "URL HTTPS de la imagen de perfil",
    "curriculum.biography": "Biografía profesional",
    "curriculum.teachingTopics": "Temas de enseñanza",
    "curriculum.saveProfile": "Guardar perfil docente",
    "curriculum.profileSaved": "Perfil docente guardado.",
    "curriculum.teacherQualification": "Gestionar una cualificación docente",
    "curriculum.action": "Acción",
    "curriculum.grant": "Conceder",
    "curriculum.remove": "Retirar",
    "curriculum.applyQualification": "Aplicar cambio de cualificación docente",
    "curriculum.qualificationGranted": "Cualificación docente concedida y notificada a la persona docente.",
    "curriculum.qualificationRemoved": "Cualificación docente retirada y notificada a la persona docente.",
    "curriculum.qualificationBlocked": "Resuelve las sesiones de clase futuras indicadas antes de retirar esta cualificación docente.",
    "curriculum.teachers": "Perfiles y cualificaciones docentes",
    "curriculum.teacherId": "ID de usuario docente",
    "teacher-qualification.granted.teacher": "Cualificación docente concedida para {targetLanguage} {curriculumLevel} el {effectiveTime, date, long} a las {effectiveTime, time, short}.",
    "teacher-qualification.removed.teacher": "Cualificación docente retirada para {targetLanguage} {curriculumLevel} el {effectiveTime, date, long} a las {effectiveTime, time, short}.",
    "class-session.teacher-assigned.teacher": "{imminent, select, true {Asignación inminente: } other {}}Tienes asignada la sesión de clase {classSessionId} el {startsAt, date, long} a las {startsAt, time, short}.",
    "class-session.reminder.teacher": "Recordatorio: la sesión de clase {classSessionId} comienza el {startsAt, date, long} a las {startsAt, time, short}.",
    "class-session.reminder.student": "Recordatorio: la sesión de clase {classSessionId} comienza el {startsAt, date, long} a las {startsAt, time, short}.",
    "absence-request.created.administrator": "El docente {teacherUserId} informó de una ausencia que afecta a las sesiones de clase {classSessionIds}. Resuelve los compromisos: {resolutionLink}",
    "class-session.teacher-removed.teacher": "Ya no tienes asignada la sesión de clase {classSessionId} del {startsAt, date, long} a las {startsAt, time, short}.",
    "class-session.teacher-substituted.teacher": "{imminent, select, true {Asignación inminente: } other {}}Eres el docente sustituto de la sesión de clase {classSessionId} del {startsAt, date, long} a las {startsAt, time, short}.",
    "class-session.teacher-substituted.student": "La sesión de clase {classSessionId} del {startsAt, date, long} a las {startsAt, time, short} estará dirigida por el docente sustituto {replacementTeacherDisplayName}. Puedes cancelar y recuperar un crédito de clase.",
    "class-session.cancelled.student": "La sesión de clase {classSessionId} del {startsAt, date, long} a las {startsAt, time, short} fue cancelada. Se devolvió un crédito de clase.",
    "class-session.cancelled.teacher": "La sesión de clase {classSessionId} del {startsAt, date, long} a las {startsAt, time, short} fue cancelada.",
    "booking.created.student": "Reserva confirmada para la sesión de clase {classSessionId} el {startsAt, date, long} a las {startsAt, time, short}. Se canjeó un crédito de clase; quedan {availableBalance, number}.",
    "booking.rescheduled.student": "Reserva trasladada de la sesión de clase {originalClassSessionId} a la sesión de clase {replacementClassSessionId} el {startsAt, date, long} a las {startsAt, time, short}. Se conservó el mismo crédito de clase.",
    "booking.cancelled.student": "Reserva cancelada para la sesión de clase {classSessionId}. {classCreditRefunded, select, true {Se devolvió un crédito de clase.} other {El crédito de clase se perdió según la regla de cancelación tardía.}} Saldo disponible: {availableBalance, number}.",
    "waitlist-entry.created.student": "Te uniste a la lista de espera de la sesión de clase {classSessionId} hasta el {expiresAt, date, long} a las {expiresAt, time, short}. No se reserva ninguna plaza ni crédito de clase; la promoción puede canjear automáticamente un crédito de clase.",
    "waitlist-entry.withdrawn.student": "Te retiraste de la lista de espera de la sesión de clase {classSessionId}. La promoción automática se detuvo; no se creó ninguna reserva ni se canjeó ningún crédito de clase.",
    "waitlist-entry.promoted.student": "{imminent, select, true {Comienza pronto: } other {}}La lista de espera confirmó la reserva {bookingId} para la sesión de clase {classSessionId} el {startsAt, date, long} a las {startsAt, time, short}. Se canjeó un crédito de clase. Puedes cancelar con reembolso hasta las {refundUntil, time, short}.",
    "waitlist-entry.ineligible.student": "La promoción de la lista de espera terminó para la sesión de clase {classSessionId}: {reasonCode, select, INSUFFICIENT_CLASS_CREDITS {ya no hay un crédito de clase disponible} SCHEDULE_CONFLICT {otro compromiso coincide ahora con esta sesión de clase} ALREADY_BOOKED {ya existe una reserva activa} CLASS_SESSION_UNAVAILABLE {la sesión de clase ya no está disponible} other {la elegibilidad cambió}}. No se creó ninguna reserva ni se canjeó ningún crédito de clase.",
    "waitlist-entry.expired.student": "La entrada de la lista de espera para la sesión de clase {classSessionId} caducó. No se creó ninguna reserva ni se canjeó ningún crédito de clase.",
    "classSession.loading": "Cargando la administración de sesiones de clase…",
    "classSession.loadError": "No pudimos cargar la administración de sesiones de clase. Inténtalo de nuevo.",
    "classSession.title": "Administración de sesiones de clase",
    "classSession.publish": "Publicar una sesión de clase",
    "classSession.lessonUnit": "Unidad didáctica",
    "classSession.teacher": "Docente",
    "classSession.localStart": "Hora local de inicio",
    "classSession.schedulingTimeZone": "Zona horaria de programación",
    "classSession.disambiguation": "Hora local repetida",
    "classSession.disambiguation.reject": "Exigir una hora inequívoca",
    "classSession.disambiguation.earlier": "Primera aparición",
    "classSession.disambiguation.later": "Segunda aparición",
    "classSession.seatCapacity": "Capacidad de plazas",
    "classSession.publishAction": "Publicar sesión de clase",
    "classSession.published": "Sesión de clase publicada por 60 minutos con capacidad de {seatCapacity} plazas.",
    "classSession.current": "Sesiones de clase publicadas",
    "classSession.resolveAbsences": "Resolver solicitudes de ausencia",
    "classSession.noAbsences": "No hay solicitudes de ausencia abiertas.",
    "classSession.absenceRequest": "Solicitud de ausencia",
    "classSession.cancellationReason": "Motivo de cancelación",
    "classSession.cancelAction": "Cancelar sesión de clase",
    "classSession.replacementTeacher": "Docente sustituto",
    "classSession.substituteAction": "Sustituir docente",
    "classSession.cancelled": "Sesión de clase cancelada; {bookings, plural, one {# reserva reembolsada} other {# reservas reembolsadas}} y {waitlist, plural, one {# entrada de lista de espera eliminada} other {# entradas de lista de espera eliminadas}}.",
    "classSession.substituted": "Docente sustituto asignado sin cambiar la hora de inicio de la sesión de clase.",
    "classSession.none": "No se ha publicado ninguna sesión de clase.",
    "classSession.capacityAction": "Cambiar capacidad de plazas",
    "classSession.capacityChanged": "Capacidad de plazas cambiada a {seatCapacity}.",
    "classSession.error": "No pudimos guardar el cambio de la sesión de clase. Revisa los datos e inténtalo de nuevo.",
    "classSession.error.invalidSeatCapacity": "La capacidad de plazas debe ser de 2 a 8.",
    "classSession.error.invalidTimeZone": "Elige una zona horaria regional con nombre para la programación.",
    "classSession.error.fold": "Elige la primera o la segunda aparición de la hora local repetida.",
    "classSession.error.gap": "Esa hora local no existe debido a una transición del horario de verano.",
    "classSession.error.invalidLocalDateTime": "Introduce una hora local válida de inicio para la sesión de clase.",
    "classSession.error.invalidLessonUnit": "Elige una unidad didáctica activa.",
    "classSession.error.qualificationRequired": "La persona docente necesita una cualificación docente correspondiente.",
    "classSession.error.availabilityRequired": "La sesión de clase completa debe caber dentro de una disponibilidad docente compatible.",
    "classSession.error.availabilityException": "Una excepción de disponibilidad se solapa con esta sesión de clase.",
    "classSession.error.scheduleConflict": "La persona docente ya tiene una sesión de clase solapada.",
    "classSession.error.notFound": "Elige una sesión de clase publicada.",
    "classSession.error.capacityBelowOccupied": "La capacidad de plazas no puede ser inferior a las plazas ocupadas.",
    "classSession.error.idempotencyKeyReused": "Ese identificador de solicitud ya se usó para otro cambio.",
    "classSession.error.attendanceSubmitted": "Esta sesión de clase no se puede cancelar después de enviar un registro de asistencia.",
    "attendance.published.student": "Asistencia de la sesión de clase {classSessionId}: {outcome, select, ATTENDED {Asistió} other {Ausente}}. Solicita una revisión antes del {reviewDeadline, date, long} a las {reviewDeadline, time, short}.{outcome, select, ATTENDED { Envía una valoración de la sesión antes del {ratingDeadline, date, long} a las {ratingDeadline, time, short}.} other {}}",
    "attendance.corrected.student": "La asistencia de la sesión de clase {classSessionId} se corrigió a {outcome, select, ATTENDED {Asistió} other {Ausente}}.",
    "attendance.corrected.teacher": "La administración de la plataforma corrigió la asistencia de la sesión de clase {classSessionId} a {outcome, select, ATTENDED {Asistió} other {Ausente}}.",
    "attendance.loading": "Cargando el trabajo de asistencia…",
    "attendance.loadError": "No pudimos cargar el trabajo de asistencia. Inténtalo de nuevo.",
    "attendance.title": "Registrar asistencia",
    "attendance.none": "No hay sesiones de clase abiertas para registrar asistencia.",
    "attendance.openRoster": "Registrar asistencia del {startsAt}",
    "attendance.rosterLoading": "Cargando la lista de clase…",
    "attendance.attended": "Asistió",
    "attendance.noShow": "Ausente",
    "attendance.submit": "Publicar asistencia",
    "attendance.published": "La asistencia se publicó.",
    "attendance.error": "No pudimos publicar la asistencia. Revisa la lista de clase e inténtalo de nuevo.",
    "attendance.correctionReason": "Motivo de la corrección",
    "attendance.error.correctionReason": "Indica un motivo de corrección de al menos 10 caracteres.",
    "attendance.error.notOpen": "La asistencia permanece sin registrar hasta que termine la sesión de clase.",
    "attendance.error.windowClosed": "El plazo docente para registrar la asistencia ha terminado.",
    "attendance.error.rosterMismatch": "Vuelve a cargar la lista de clase antes de publicar la asistencia.",
    "attendance.error.notFound": "Esta sesión de clase no está disponible para registrar asistencia.",
    "attendance.error.idempotency": "Este identificador de solicitud ya se usó con otros datos de asistencia.",
    "learning-feedback.submitted.student": "Los comentarios de aprendizaje están disponibles para la sesión de clase {classSessionId}.",
    "feedback.title": "Comentarios de aprendizaje",
    "feedback.studentTitle": "Comentarios y valoraciones de sesiones",
    "feedback.loading": "Cargando comentarios…",
    "feedback.loadError": "No pudimos cargar los comentarios. Inténtalo de nuevo.",
    "feedback.empty": "No hay reservas con asistencia abiertas para comentarios de aprendizaje.",
    "feedback.studentEmpty": "Aún no hay sesiones con asistencia para valorar.",
    "feedback.notSubmitted": "Los comentarios de aprendizaje aún no se han enviado.",
    "feedback.deadline": "Envía o revisa antes de {deadline}.",
    "feedback.strengths": "Fortalezas observadas (hasta tres)",
    "feedback.focuses": "Enfoque sugerido (hasta tres)",
    "feedback.observations": "Observaciones",
    "feedback.nextPractice": "Próxima práctica",
    "feedback.saveDraft": "Guardar borrador privado",
    "feedback.submit": "Enviar comentarios de aprendizaje",
    "feedback.revise": "Revisar comentarios de aprendizaje",
    "feedback.saved": "Comentarios de aprendizaje guardados.",
    "feedback.error": "No pudimos guardar los comentarios de aprendizaje. Revisa el contenido y el plazo.",
    "feedback.skill.LISTENING": "Comprensión auditiva",
    "feedback.skill.READING": "Lectura",
    "feedback.skill.SPOKEN_INTERACTION": "Interacción oral",
    "feedback.skill.SPOKEN_PRODUCTION": "Producción oral",
    "feedback.skill.WRITING": "Escritura",
    "feedback.skill.VOCABULARY": "Vocabulario",
    "feedback.skill.GRAMMAR": "Gramática",
    "feedback.skill.PRONUNCIATION": "Pronunciación",
    "rating.deadline": "Envía o edita tu valoración privada antes de {deadline}.",
    "rating.overall": "Valoración general de la sesión",
    "rating.positiveTags": "Lo que funcionó bien",
    "rating.improvementTags": "Lo que podría mejorar",
    "rating.comment": "Comentario privado para administradores de la plataforma",
    "rating.submit": "Enviar valoración de la sesión",
    "rating.edit": "Guardar valoración editada",
    "rating.saved": "Valoración guardada de forma privada.",
    "rating.error": "No pudimos guardar tu valoración. Revisa la puntuación y el plazo.",
    "rating.closed": "El plazo para editar la valoración de la sesión ha terminado.",
    "rating.tag.CLEAR_EXPLANATIONS": "Explicaciones claras",
    "rating.tag.SUPPORTIVE": "Apoyo",
    "rating.tag.ENGAGING": "Atractiva",
    "rating.tag.USEFUL_PRACTICE": "Práctica útil",
    "rating.tag.PACING": "Ritmo",
    "rating.tag.AUDIO_QUALITY": "Calidad del audio",
    "rating.tag.MORE_CORRECTION": "Más correcciones",
    "rating.tag.MORE_SPEAKING_TIME": "Más tiempo para hablar",
    "quality.title": "Calidad del aprendizaje",
    "quality.loading": "Cargando registros privados de calidad…",
    "quality.error": "No pudimos cargar los registros privados de calidad. Inténtalo de nuevo.",
    "quality.empty": "No hay comentarios ni valoraciones privadas.",
    "quality.feedbackState": "Estado de los comentarios de aprendizaje: {state}",
    "quality.feedbackState.DRAFT": "Borrador privado",
    "quality.feedbackState.SUBMITTED": "Enviados",
    "quality.rating": "Valoración de la sesión: {rating} de 5.",
    "progress.loading": "Cargando el progreso del curso…",
    "progress.loadError": "No pudimos cargar el progreso del curso. Inténtalo de nuevo.",
    "progress.title": "Progreso del curso",
    "progress.none": "Aún no hay progreso del curso disponible.",
    "progress.label": "Progreso de {course}",
    "progress.summary": "{completed} de {total} unidades didácticas activas completadas",
    "progress.history": "Historial de aprendizaje",
    "progress.activeHistory": "{title} — cuenta para el progreso",
    "progress.retiredHistory": "{title} — historial retirado",
    "classSession.error.disruptionResolved": "Esta interrupción de sesión de clase ya se resolvió y no se puede cambiar.",
    "classSession.error.invalidReason": "Indica un motivo de cancelación de entre 10 y 500 caracteres.",
    "classSession.error.replacementRequired": "Elige a otro docente como sustituto.",
    "classSession.error.alreadyStarted": "Esta interrupción ya no se puede resolver porque la sesión de clase ha comenzado.",
    "auth.loading": "Comprobando tu sesión…",
    "auth.error": "No pudimos verificar tu sesión. Inténtalo de nuevo.",
    "auth.signIn": "Iniciar sesión",
    "teacherSchedule.loading": "Cargando sesiones de clase asignadas…",
    "teacherSchedule.loadError": "No pudimos cargar tus sesiones de clase asignadas. Inténtalo de nuevo.",
    "teacherSchedule.title": "Sesiones de clase asignadas",
    "teacherSchedule.help": "Informar una solicitud de ausencia mantiene intactas cada sesión de clase publicada y sus reservas hasta que la administración de la plataforma la resuelva.",
    "teacherSchedule.none": "No tienes próximas sesiones de clase asignadas.",
    "teacherSchedule.choose": "Elige las sesiones de clase que no puedes dirigir",
    "teacherSchedule.report": "Informar ausencia",
    "teacherSchedule.absenceReported": "La solicitud de ausencia se envió para que la administración de la plataforma la resuelva.",
    "teacherSchedule.error": "No pudimos enviar la solicitud de ausencia. Revisa las sesiones de clase seleccionadas e inténtalo de nuevo.",
    "teacherSchedule.requests": "Solicitudes de ausencia",
    "teacherSchedule.noRequests": "No tienes solicitudes de ausencia.",
    "teacherSchedule.requestOpen": "Solicitud de ausencia abierta que afecta a {count, plural, one {# sesión de clase} other {# sesiones de clase}}.",
    "teacherSchedule.requestResolved": "Solicitud de ausencia resuelta que afecta a {count, plural, one {# sesión de clase} other {# sesiones de clase}}.",
    "learningAccess.loading": "Cargando los materiales de la unidad y el acceso al aula…",
    "learningAccess.loadError": "No pudimos cargar los materiales de la unidad y el acceso al aula. Inténtalo de nuevo.",
    "learningAccess.title": "Materiales de la unidad y aula",
    "learningAccess.help": "Los materiales de la unidad siguen tu reserva, finalización o asignación docente. Solo puedes entrar al aula cerca de la hora de la sesión de clase.",
    "learningAccess.none": "Ninguna sesión de clase ofrece acceso de aprendizaje en este momento.",
    "learningAccess.openMaterials": "Abrir materiales de la unidad",
    "learningAccess.enterClassroom": "Entrar al aula",
    "learningAccess.materials": "Materiales de la unidad",
    "learningAccess.classroom": "Acceso al aula",
    "learningAccess.noMaterials": "Esta unidad de lección no tiene materiales.",
    "learningAccess.classroomReady": "El aula simulada está lista. Entrar no registra la asistencia.",
    "learningAccess.error": "Ese acceso de aprendizaje no está disponible ahora. Comprueba tu relación y la hora de la sesión de clase.",
    "availability.loading": "Cargando la disponibilidad docente…",
    "availability.loadError": "No pudimos cargar la disponibilidad docente. Inténtalo de nuevo.",
    "availability.title": "Disponibilidad docente semanal",
    "availability.timeZone": "Zona horaria docente: {timeZone}",
    "availability.dstHelp": "Las horas semanales conservan estas horas de reloj cuando cambia el horario de verano. Las fechas de vigencia futuras preservan el contexto anterior.",
    "availability.weekday": "Día de la semana",
    "availability.startTime": "Hora de inicio",
    "availability.endTime": "Hora de fin",
    "availability.effectiveFrom": "Vigente desde",
    "availability.addRange": "Añadir horario semanal",
    "availability.effectiveUntil": "Vigente hasta",
    "availability.endRange": "Finalizar horario semanal",
    "availability.rangeSaved": "Disponibilidad docente semanal guardada.",
    "availability.rangeDescription": "{weekday}, {start}–{end} desde {from}",
    "availability.rangeDescriptionEnded": "{weekday}, {start}–{end} desde {from} hasta {until}",
    "availability.ranges": "Horarios semanales guardados",
    "availability.exceptions": "Excepciones de disponibilidad",
    "availability.unavailableFrom": "No disponible desde",
    "availability.unavailableUntil": "No disponible hasta",
    "availability.repeatedStart": "Hora de inicio repetida",
    "availability.repeatedEnd": "Hora de fin repetida",
    "availability.addException": "Añadir excepción de disponibilidad",
    "availability.exceptionSaved": "Excepción de disponibilidad guardada.",
    "availability.exceptionDescription": "{start}–{end}",
    "availability.savedExceptions": "Excepciones de disponibilidad guardadas",
    "availability.removeException": "Eliminar excepción de disponibilidad",
    "availability.createAbsenceRequest": "Crear una solicitud de ausencia",
    "availability.saveError": "No pudimos guardar el cambio. Revisa los datos e inténtalo de nuevo.",
    "availability.disambiguation.reject": "Exigir una hora inequívoca",
    "availability.disambiguation.earlier": "Primera aparición",
    "availability.disambiguation.later": "Segunda aparición",
    "availability.error.exceptionNotFound": "No se encontró la excepción de disponibilidad.",
    "availability.error.idempotencyKeyReused": "Ese identificador de solicitud ya se usó para otro cambio.",
    "availability.error.invalidRange": "Introduce una hora de fin posterior al inicio y una fecha de vigencia válida.",
    "availability.error.invalidEffectiveDate": "Elige una fecha de vigencia que no se solape con un horario semanal posterior.",
    "availability.error.invalidLocalDateTime": "Introduce fechas y horas locales de inicio y fin válidas.",
    "availability.error.invalidTimeRange": "La hora final de indisponibilidad debe ser posterior a la inicial.",
    "availability.error.invalidTimeZone": "Elige una zona horaria regional con nombre.",
    "availability.error.fold": "Elige la primera o la segunda aparición de la hora local repetida.",
    "availability.error.gap": "Esa hora local no existe debido a una transición del horario de verano.",
    "availability.error.sessionOverlap": "Una sesión de clase publicada ocupa este horario. Crea una solicitud de ausencia.",
    "discovery.title": "Descubrir sesiones de clase",
    "discovery.filters": "Filtros de descubrimiento",
    "discovery.targetLanguage": "Idioma objetivo",
    "discovery.curriculumLevel": "Nivel curricular",
    "discovery.anyLevel": "Cualquier nivel curricular",
    "discovery.teacher": "Docente",
    "discovery.anyTeacher": "Cualquier docente",
    "discovery.topics": "Temas (coincidir con cualquiera)",
    "discovery.localDate": "Fecha local",
    "discovery.localDateHelp": "Déjalo en blanco para buscar las próximas siete fechas en {timeZone}.",
    "discovery.search": "Buscar sesiones de clase",
    "discovery.savePlacement": "Guardar nivel curricular del estudiante",
    "discovery.placementSaved": "Nivel curricular del estudiante guardado.",
    "discovery.loading": "Buscando sesiones de clase…",
    "discovery.error": "No pudimos cargar el descubrimiento de sesiones de clase. Inténtalo de nuevo.",
    "discovery.none": "Ninguna sesión de clase disponible coincide con estos filtros.",
    "discovery.results": "Resultados de sesiones de clase",
    "discovery.seatsAvailable": "{occupied} de {total} plazas ocupadas; hay plazas disponibles",
    "discovery.waitlistOpen": "{occupied} de {total} plazas ocupadas; lista de espera abierta",
    "discovery.teacherProfile": "Perfil docente",
    "discovery.completedSessions": "{count, plural, one {# sesión de clase completada} other {# sesiones de clase completadas}}",
    "discovery.taughtLanguages": "Idiomas enseñados: {languages}",
    "discovery.qualifiedLevels": "Niveles curriculares habilitados: {levels}",
    "discovery.teachingTopics": "Temas de enseñanza: {topics}",
    "discovery.objectives": "Objetivos",
    "discovery.loadMore": "Cargar más sesiones de clase",
    "booking.bookAction": "Reservar sesión de clase",
    "booking.cancelAction": "Cancelar reserva",
    "booking.rescheduleAction": "Reprogramar reserva",
    "booking.activeTitle": "Mis reservas activas",
    "booking.active": "Reserva activa",
    "booking.cancelFor": "Cancelar reserva del {startsAt, date, long} a las {startsAt, time, short}",
    "booking.rescheduleFromTo": "Reprogramar reserva del {originalStartsAt, date, long} a las {originalStartsAt, time, short} para el {replacementStartsAt, date, long} a las {replacementStartsAt, time, short}",
    "booking.booking": "Reservando sesión de clase…",
    "booking.cancelling": "Cancelando reserva…",
    "booking.rescheduling": "Reprogramando reserva…",
    "booking.created": "Reserva confirmada. Se canjeó un crédito de clase.",
    "booking.cancelled.refunded": "Reserva cancelada. Se devolvió un crédito de clase.",
    "booking.cancelled.forfeited": "Reserva cancelada. El crédito de clase se perdió según la regla de cancelación tardía.",
    "booking.rescheduled": "Reserva reprogramada. Se conservó el mismo crédito de clase.",
    "booking.error": "No pudimos completar el cambio de reserva. Revisa los detalles e inténtalo de nuevo.",
    "booking.error.CLASS_SESSION_NOT_FOUND": "Esta sesión de clase ya no está disponible.",
    "booking.error.BOOKING_WINDOW_CLOSED": "Las reservas cierran 30 minutos antes del inicio de la sesión de clase.",
    "booking.error.SESSION_FULL": "Esta sesión de clase está llena.",
    "booking.error.INSUFFICIENT_CLASS_CREDITS": "Se necesita un crédito de clase disponible para reservar.",
    "booking.error.SCHEDULE_CONFLICT": "Esta sesión de clase coincide con otro compromiso activo como estudiante o docente.",
    "booking.error.ALREADY_BOOKED": "Ya tienes una reserva activa para esta sesión de clase.",
    "booking.error.BOOKING_NOT_FOUND": "Esta reserva ya no está disponible.",
    "booking.error.BOOKING_NOT_ACTIVE": "Solo se puede cancelar una reserva activa.",
    "booking.error.CANCELLATION_WINDOW_CLOSED": "No se puede cancelar una reserva después del inicio de su sesión de clase.",
    "booking.error.LESSON_UNIT_MISMATCH": "Elige una sesión de clase de reemplazo que imparta la misma unidad didáctica.",
    "booking.error.IDEMPOTENCY_KEY_REUSED": "Ese identificador de solicitud ya se usó para otro cambio de reserva.",
    "waitlist.joinAction": "Unirse a la lista de espera",
    "waitlist.joining": "Uniéndote a la lista de espera…",
    "waitlist.withdrawAction": "Retirarse de la lista de espera",
    "waitlist.withdrawing": "Retirándote de la lista de espera…",
    "waitlist.withdrawFor": "Retirarse de la lista de espera del {startsAt, date, long} a las {startsAt, time, short}",
    "waitlist.active": "Entrada de lista de espera activa",
    "waitlist.joined": "Te uniste a la lista de espera. No se reserva ninguna plaza ni crédito de clase.",
    "waitlist.withdrawn": "Te retiraste de la lista de espera. No se creó ninguna reserva ni se canjeó ningún crédito de clase.",
    "waitlist.promotionWon": "La promoción terminó primero. Tu reserva está activa; cancélala si ya no quieres la plaza.",
    "waitlist.error": "No pudimos completar el cambio de la lista de espera. Revisa los detalles e inténtalo de nuevo.",
    "waitlist.error.CLASS_SESSION_NOT_FOUND": "Esta sesión de clase ya no está disponible.",
    "waitlist.error.WAITLIST_NOT_OPEN": "La lista de espera cierra dos horas antes del inicio de la sesión de clase.",
    "waitlist.error.SESSION_NOT_FULL": "Esta sesión de clase tiene una plaza disponible; resérvala en su lugar.",
    "waitlist.error.INSUFFICIENT_CLASS_CREDITS": "Se necesita un crédito de clase disponible para unirse a la lista de espera.",
    "waitlist.error.SCHEDULE_CONFLICT": "Esta sesión de clase coincide con otro compromiso activo como estudiante o docente.",
    "waitlist.error.ALREADY_BOOKED": "Ya tienes una reserva activa para esta sesión de clase.",
    "waitlist.error.ALREADY_WAITLISTED": "Ya tienes una entrada activa en la lista de espera para esta sesión de clase.",
    "waitlist.error.WAITLIST_ENTRY_NOT_FOUND": "Esta entrada de la lista de espera ya no está disponible.",
    "waitlist.error.WAITLIST_ENTRY_NOT_ACTIVE": "Solo se puede retirar una entrada activa de la lista de espera.",
    "waitlist.error.IDEMPOTENCY_KEY_REUSED": "Ese identificador de solicitud ya se usó para otro cambio de la lista de espera.",
  },
} as const;
